version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0_121
install:
  - choco install maven
  - mvn --version
build_script:
  - mvn clean package -Dmaven.test.skip=true
test_script:
  - mvn test