//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 02:11:12 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mesa.org/xml/B2MML-V0600-AllExtensions")
package org.mesa.xml.b2mml_allextensions;
