//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 02:10:24 PM CST 
//


package org.mesa.xml.b2mml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BatchProductionRecordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BatchProductionRecordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-V0600}BatchProductionRecordEntryType"/>
 *         &lt;element name="EquipmentScope" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="PublishedDate" type="{http://www.mesa.org/xml/B2MML-V0600}DateTimeType" minOccurs="0"/>
 *         &lt;element name="CreationDate" type="{http://www.mesa.org/xml/B2MML-V0600}DateTimeType" minOccurs="0"/>
 *         &lt;element name="BatchID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="BatchProductionRecordSpec" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="CampaignID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="ChangeIndication" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Delimiter" type="{http://www.mesa.org/xml/B2MML-V0600}TextType" minOccurs="0"/>
 *         &lt;element name="EquipmentID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="ExpirationDate" type="{http://www.mesa.org/xml/B2MML-V0600}DateTimeType" minOccurs="0"/>
 *         &lt;element name="Language" type="{http://www.mesa.org/xml/B2MML-V0600}CodeType" minOccurs="0"/>
 *         &lt;element name="LastChangedDate" type="{http://www.mesa.org/xml/B2MML-V0600}DateTimeType" minOccurs="0"/>
 *         &lt;element name="LotID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="MaterialDefinitionID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="PhysicalAssetID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="RecordStatus" type="{http://www.mesa.org/xml/B2MML-V0600}CodeType" minOccurs="0"/>
 *         &lt;element name="Version" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="ChangeHistory" type="{http://www.mesa.org/xml/B2MML-V0600}ChangeHistoryType" minOccurs="0"/>
 *         &lt;element name="Comments" type="{http://www.mesa.org/xml/B2MML-V0600}CommentsType" minOccurs="0"/>
 *         &lt;element name="ControlRecipes" type="{http://www.mesa.org/xml/B2MML-V0600}ControlRecipesType" minOccurs="0"/>
 *         &lt;element name="DataSets" type="{http://www.mesa.org/xml/B2MML-V0600}DataSetsType" minOccurs="0"/>
 *         &lt;element name="Events" type="{http://www.mesa.org/xml/B2MML-V0600}EventsType" minOccurs="0"/>
 *         &lt;element name="MasterRecipes" type="{http://www.mesa.org/xml/B2MML-V0600}MasterRecipesType" minOccurs="0"/>
 *         &lt;element name="PersonnelIdentification" type="{http://www.mesa.org/xml/B2MML-V0600}PersonnelIdentificationType" minOccurs="0"/>
 *         &lt;element name="OperationsDefinitions" type="{http://www.mesa.org/xml/B2MML-V0600}OperationsDefinitionsType" minOccurs="0"/>
 *         &lt;element name="OperationsPerformances" type="{http://www.mesa.org/xml/B2MML-V0600}OperationsPerformancesType" minOccurs="0"/>
 *         &lt;element name="OperationsSchedules" type="{http://www.mesa.org/xml/B2MML-V0600}OperationsSchedulesType" minOccurs="0"/>
 *         &lt;element name="ProductDefinitions" type="{http://www.mesa.org/xml/B2MML-V0600}ProductDefinitionsType" minOccurs="0"/>
 *         &lt;element name="ProductionPerformances" type="{http://www.mesa.org/xml/B2MML-V0600}ProductionPerformancesType" minOccurs="0"/>
 *         &lt;element name="ProductionSchedules" type="{http://www.mesa.org/xml/B2MML-V0600}ProductionSchedulesType" minOccurs="0"/>
 *         &lt;element name="RecipeElements" type="{http://www.mesa.org/xml/B2MML-V0600}RecipeElementsType" minOccurs="0"/>
 *         &lt;element name="ResourceQualifications" type="{http://www.mesa.org/xml/B2MML-V0600}ResourceQualificationsType" minOccurs="0"/>
 *         &lt;element name="Samples" type="{http://www.mesa.org/xml/B2MML-V0600}SamplesType" minOccurs="0"/>
 *         &lt;element name="WorkDirectives" type="{http://www.mesa.org/xml/B2MML-V0600}WorkDirectivesType" minOccurs="0"/>
 *         &lt;element name="WorkMasters" type="{http://www.mesa.org/xml/B2MML-V0600}WorkMastersType" minOccurs="0"/>
 *         &lt;element name="WorkPerformances" type="{http://www.mesa.org/xml/B2MML-V0600}WorkPerformancesType" minOccurs="0"/>
 *         &lt;element name="WorkSchedules" type="{http://www.mesa.org/xml/B2MML-V0600}WorkSchedulesType" minOccurs="0"/>
 *         &lt;element name="BatchProductionRecord" type="{http://www.mesa.org/xml/B2MML-V0600}BatchProductionRecordType" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-V0600-AllExtensions}BatchProductionRecord" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BatchProductionRecordType", propOrder = {
    "id",
    "entryID",
    "objectType",
    "timeStamp",
    "externalReference",
    "description",
    "equipmentScope",
    "publishedDate",
    "creationDate",
    "batchID",
    "batchProductionRecordSpec",
    "campaignID",
    "changeIndication",
    "delimiter",
    "equipmentID",
    "expirationDate",
    "language",
    "lastChangedDate",
    "lotID",
    "materialDefinitionID",
    "physicalAssetID",
    "recordStatus",
    "version",
    "changeHistory",
    "comments",
    "controlRecipes",
    "dataSets",
    "events",
    "masterRecipes",
    "personnelIdentification",
    "operationsDefinitions",
    "operationsPerformances",
    "operationsSchedules",
    "productDefinitions",
    "productionPerformances",
    "productionSchedules",
    "recipeElements",
    "resourceQualifications",
    "samples",
    "workDirectives",
    "workMasters",
    "workPerformances",
    "workSchedules",
    "batchProductionRecord"
})
public class BatchProductionRecordType {

    @XmlElement(name = "ID", required = true)
    protected IdentifierType id;
    @XmlElement(name = "EntryID", required = true)
    protected IdentifierType entryID;
    @XmlElement(name = "ObjectType", required = true)
    protected RecordObjectTypeType objectType;
    @XmlElement(name = "TimeStamp")
    protected DateTimeType timeStamp;
    @XmlElement(name = "ExternalReference")
    protected IdentifierType externalReference;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "EquipmentScope")
    protected IdentifierType equipmentScope;
    @XmlElement(name = "PublishedDate")
    protected DateTimeType publishedDate;
    @XmlElement(name = "CreationDate")
    protected DateTimeType creationDate;
    @XmlElement(name = "BatchID")
    protected IdentifierType batchID;
    @XmlElement(name = "BatchProductionRecordSpec")
    protected IdentifierType batchProductionRecordSpec;
    @XmlElement(name = "CampaignID")
    protected IdentifierType campaignID;
    @XmlElement(name = "ChangeIndication")
    protected String changeIndication;
    @XmlElement(name = "Delimiter")
    protected TextType delimiter;
    @XmlElement(name = "EquipmentID")
    protected IdentifierType equipmentID;
    @XmlElement(name = "ExpirationDate")
    protected DateTimeType expirationDate;
    @XmlElement(name = "Language")
    protected CodeType language;
    @XmlElement(name = "LastChangedDate")
    protected DateTimeType lastChangedDate;
    @XmlElement(name = "LotID")
    protected IdentifierType lotID;
    @XmlElement(name = "MaterialDefinitionID")
    protected IdentifierType materialDefinitionID;
    @XmlElement(name = "PhysicalAssetID")
    protected IdentifierType physicalAssetID;
    @XmlElement(name = "RecordStatus")
    protected CodeType recordStatus;
    @XmlElement(name = "Version")
    protected IdentifierType version;
    @XmlElement(name = "ChangeHistory")
    protected ChangeHistoryType changeHistory;
    @XmlElement(name = "Comments")
    protected CommentsType comments;
    @XmlElement(name = "ControlRecipes")
    protected ControlRecipesType controlRecipes;
    @XmlElement(name = "DataSets")
    protected DataSetsType dataSets;
    @XmlElement(name = "Events")
    protected EventsType events;
    @XmlElement(name = "MasterRecipes")
    protected MasterRecipesType masterRecipes;
    @XmlElement(name = "PersonnelIdentification")
    protected PersonnelIdentificationType personnelIdentification;
    @XmlElement(name = "OperationsDefinitions")
    protected OperationsDefinitionsType operationsDefinitions;
    @XmlElement(name = "OperationsPerformances")
    protected OperationsPerformancesType operationsPerformances;
    @XmlElement(name = "OperationsSchedules")
    protected OperationsSchedulesType operationsSchedules;
    @XmlElement(name = "ProductDefinitions")
    protected ProductDefinitionsType productDefinitions;
    @XmlElement(name = "ProductionPerformances")
    protected ProductionPerformancesType productionPerformances;
    @XmlElement(name = "ProductionSchedules")
    protected ProductionSchedulesType productionSchedules;
    @XmlElement(name = "RecipeElements")
    protected RecipeElementsType recipeElements;
    @XmlElement(name = "ResourceQualifications")
    protected ResourceQualificationsType resourceQualifications;
    @XmlElement(name = "Samples")
    protected SamplesType samples;
    @XmlElement(name = "WorkDirectives")
    protected WorkDirectivesType workDirectives;
    @XmlElement(name = "WorkMasters")
    protected WorkMastersType workMasters;
    @XmlElement(name = "WorkPerformances")
    protected WorkPerformancesType workPerformances;
    @XmlElement(name = "WorkSchedules")
    protected WorkSchedulesType workSchedules;
    @XmlElement(name = "BatchProductionRecord")
    protected BatchProductionRecordType batchProductionRecord;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the entryID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getEntryID() {
        return entryID;
    }

    /**
     * Sets the value of the entryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setEntryID(IdentifierType value) {
        this.entryID = value;
    }

    /**
     * Gets the value of the objectType property.
     * 
     * @return
     *     possible object is
     *     {@link RecordObjectTypeType }
     *     
     */
    public RecordObjectTypeType getObjectType() {
        return objectType;
    }

    /**
     * Sets the value of the objectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordObjectTypeType }
     *     
     */
    public void setObjectType(RecordObjectTypeType value) {
        this.objectType = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeType }
     *     
     */
    public DateTimeType getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeType }
     *     
     */
    public void setTimeStamp(DateTimeType value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the externalReference property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getExternalReference() {
        return externalReference;
    }

    /**
     * Sets the value of the externalReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setExternalReference(IdentifierType value) {
        this.externalReference = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the equipmentScope property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getEquipmentScope() {
        return equipmentScope;
    }

    /**
     * Sets the value of the equipmentScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setEquipmentScope(IdentifierType value) {
        this.equipmentScope = value;
    }

    /**
     * Gets the value of the publishedDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeType }
     *     
     */
    public DateTimeType getPublishedDate() {
        return publishedDate;
    }

    /**
     * Sets the value of the publishedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeType }
     *     
     */
    public void setPublishedDate(DateTimeType value) {
        this.publishedDate = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeType }
     *     
     */
    public DateTimeType getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeType }
     *     
     */
    public void setCreationDate(DateTimeType value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the batchID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getBatchID() {
        return batchID;
    }

    /**
     * Sets the value of the batchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setBatchID(IdentifierType value) {
        this.batchID = value;
    }

    /**
     * Gets the value of the batchProductionRecordSpec property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getBatchProductionRecordSpec() {
        return batchProductionRecordSpec;
    }

    /**
     * Sets the value of the batchProductionRecordSpec property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setBatchProductionRecordSpec(IdentifierType value) {
        this.batchProductionRecordSpec = value;
    }

    /**
     * Gets the value of the campaignID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getCampaignID() {
        return campaignID;
    }

    /**
     * Sets the value of the campaignID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setCampaignID(IdentifierType value) {
        this.campaignID = value;
    }

    /**
     * Gets the value of the changeIndication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeIndication() {
        return changeIndication;
    }

    /**
     * Sets the value of the changeIndication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeIndication(String value) {
        this.changeIndication = value;
    }

    /**
     * Gets the value of the delimiter property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getDelimiter() {
        return delimiter;
    }

    /**
     * Sets the value of the delimiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setDelimiter(TextType value) {
        this.delimiter = value;
    }

    /**
     * Gets the value of the equipmentID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getEquipmentID() {
        return equipmentID;
    }

    /**
     * Sets the value of the equipmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setEquipmentID(IdentifierType value) {
        this.equipmentID = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeType }
     *     
     */
    public DateTimeType getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeType }
     *     
     */
    public void setExpirationDate(DateTimeType value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setLanguage(CodeType value) {
        this.language = value;
    }

    /**
     * Gets the value of the lastChangedDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeType }
     *     
     */
    public DateTimeType getLastChangedDate() {
        return lastChangedDate;
    }

    /**
     * Sets the value of the lastChangedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeType }
     *     
     */
    public void setLastChangedDate(DateTimeType value) {
        this.lastChangedDate = value;
    }

    /**
     * Gets the value of the lotID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getLotID() {
        return lotID;
    }

    /**
     * Sets the value of the lotID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setLotID(IdentifierType value) {
        this.lotID = value;
    }

    /**
     * Gets the value of the materialDefinitionID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getMaterialDefinitionID() {
        return materialDefinitionID;
    }

    /**
     * Sets the value of the materialDefinitionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setMaterialDefinitionID(IdentifierType value) {
        this.materialDefinitionID = value;
    }

    /**
     * Gets the value of the physicalAssetID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getPhysicalAssetID() {
        return physicalAssetID;
    }

    /**
     * Sets the value of the physicalAssetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setPhysicalAssetID(IdentifierType value) {
        this.physicalAssetID = value;
    }

    /**
     * Gets the value of the recordStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getRecordStatus() {
        return recordStatus;
    }

    /**
     * Sets the value of the recordStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setRecordStatus(CodeType value) {
        this.recordStatus = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setVersion(IdentifierType value) {
        this.version = value;
    }

    /**
     * Gets the value of the changeHistory property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeHistoryType }
     *     
     */
    public ChangeHistoryType getChangeHistory() {
        return changeHistory;
    }

    /**
     * Sets the value of the changeHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeHistoryType }
     *     
     */
    public void setChangeHistory(ChangeHistoryType value) {
        this.changeHistory = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link CommentsType }
     *     
     */
    public CommentsType getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentsType }
     *     
     */
    public void setComments(CommentsType value) {
        this.comments = value;
    }

    /**
     * Gets the value of the controlRecipes property.
     * 
     * @return
     *     possible object is
     *     {@link ControlRecipesType }
     *     
     */
    public ControlRecipesType getControlRecipes() {
        return controlRecipes;
    }

    /**
     * Sets the value of the controlRecipes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlRecipesType }
     *     
     */
    public void setControlRecipes(ControlRecipesType value) {
        this.controlRecipes = value;
    }

    /**
     * Gets the value of the dataSets property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetsType }
     *     
     */
    public DataSetsType getDataSets() {
        return dataSets;
    }

    /**
     * Sets the value of the dataSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetsType }
     *     
     */
    public void setDataSets(DataSetsType value) {
        this.dataSets = value;
    }

    /**
     * Gets the value of the events property.
     * 
     * @return
     *     possible object is
     *     {@link EventsType }
     *     
     */
    public EventsType getEvents() {
        return events;
    }

    /**
     * Sets the value of the events property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventsType }
     *     
     */
    public void setEvents(EventsType value) {
        this.events = value;
    }

    /**
     * Gets the value of the masterRecipes property.
     * 
     * @return
     *     possible object is
     *     {@link MasterRecipesType }
     *     
     */
    public MasterRecipesType getMasterRecipes() {
        return masterRecipes;
    }

    /**
     * Sets the value of the masterRecipes property.
     * 
     * @param value
     *     allowed object is
     *     {@link MasterRecipesType }
     *     
     */
    public void setMasterRecipes(MasterRecipesType value) {
        this.masterRecipes = value;
    }

    /**
     * Gets the value of the personnelIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link PersonnelIdentificationType }
     *     
     */
    public PersonnelIdentificationType getPersonnelIdentification() {
        return personnelIdentification;
    }

    /**
     * Sets the value of the personnelIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonnelIdentificationType }
     *     
     */
    public void setPersonnelIdentification(PersonnelIdentificationType value) {
        this.personnelIdentification = value;
    }

    /**
     * Gets the value of the operationsDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsDefinitionsType }
     *     
     */
    public OperationsDefinitionsType getOperationsDefinitions() {
        return operationsDefinitions;
    }

    /**
     * Sets the value of the operationsDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsDefinitionsType }
     *     
     */
    public void setOperationsDefinitions(OperationsDefinitionsType value) {
        this.operationsDefinitions = value;
    }

    /**
     * Gets the value of the operationsPerformances property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsPerformancesType }
     *     
     */
    public OperationsPerformancesType getOperationsPerformances() {
        return operationsPerformances;
    }

    /**
     * Sets the value of the operationsPerformances property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsPerformancesType }
     *     
     */
    public void setOperationsPerformances(OperationsPerformancesType value) {
        this.operationsPerformances = value;
    }

    /**
     * Gets the value of the operationsSchedules property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsSchedulesType }
     *     
     */
    public OperationsSchedulesType getOperationsSchedules() {
        return operationsSchedules;
    }

    /**
     * Sets the value of the operationsSchedules property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsSchedulesType }
     *     
     */
    public void setOperationsSchedules(OperationsSchedulesType value) {
        this.operationsSchedules = value;
    }

    /**
     * Gets the value of the productDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link ProductDefinitionsType }
     *     
     */
    public ProductDefinitionsType getProductDefinitions() {
        return productDefinitions;
    }

    /**
     * Sets the value of the productDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductDefinitionsType }
     *     
     */
    public void setProductDefinitions(ProductDefinitionsType value) {
        this.productDefinitions = value;
    }

    /**
     * Gets the value of the productionPerformances property.
     * 
     * @return
     *     possible object is
     *     {@link ProductionPerformancesType }
     *     
     */
    public ProductionPerformancesType getProductionPerformances() {
        return productionPerformances;
    }

    /**
     * Sets the value of the productionPerformances property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductionPerformancesType }
     *     
     */
    public void setProductionPerformances(ProductionPerformancesType value) {
        this.productionPerformances = value;
    }

    /**
     * Gets the value of the productionSchedules property.
     * 
     * @return
     *     possible object is
     *     {@link ProductionSchedulesType }
     *     
     */
    public ProductionSchedulesType getProductionSchedules() {
        return productionSchedules;
    }

    /**
     * Sets the value of the productionSchedules property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductionSchedulesType }
     *     
     */
    public void setProductionSchedules(ProductionSchedulesType value) {
        this.productionSchedules = value;
    }

    /**
     * Gets the value of the recipeElements property.
     * 
     * @return
     *     possible object is
     *     {@link RecipeElementsType }
     *     
     */
    public RecipeElementsType getRecipeElements() {
        return recipeElements;
    }

    /**
     * Sets the value of the recipeElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipeElementsType }
     *     
     */
    public void setRecipeElements(RecipeElementsType value) {
        this.recipeElements = value;
    }

    /**
     * Gets the value of the resourceQualifications property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceQualificationsType }
     *     
     */
    public ResourceQualificationsType getResourceQualifications() {
        return resourceQualifications;
    }

    /**
     * Sets the value of the resourceQualifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceQualificationsType }
     *     
     */
    public void setResourceQualifications(ResourceQualificationsType value) {
        this.resourceQualifications = value;
    }

    /**
     * Gets the value of the samples property.
     * 
     * @return
     *     possible object is
     *     {@link SamplesType }
     *     
     */
    public SamplesType getSamples() {
        return samples;
    }

    /**
     * Sets the value of the samples property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamplesType }
     *     
     */
    public void setSamples(SamplesType value) {
        this.samples = value;
    }

    /**
     * Gets the value of the workDirectives property.
     * 
     * @return
     *     possible object is
     *     {@link WorkDirectivesType }
     *     
     */
    public WorkDirectivesType getWorkDirectives() {
        return workDirectives;
    }

    /**
     * Sets the value of the workDirectives property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkDirectivesType }
     *     
     */
    public void setWorkDirectives(WorkDirectivesType value) {
        this.workDirectives = value;
    }

    /**
     * Gets the value of the workMasters property.
     * 
     * @return
     *     possible object is
     *     {@link WorkMastersType }
     *     
     */
    public WorkMastersType getWorkMasters() {
        return workMasters;
    }

    /**
     * Sets the value of the workMasters property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkMastersType }
     *     
     */
    public void setWorkMasters(WorkMastersType value) {
        this.workMasters = value;
    }

    /**
     * Gets the value of the workPerformances property.
     * 
     * @return
     *     possible object is
     *     {@link WorkPerformancesType }
     *     
     */
    public WorkPerformancesType getWorkPerformances() {
        return workPerformances;
    }

    /**
     * Sets the value of the workPerformances property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkPerformancesType }
     *     
     */
    public void setWorkPerformances(WorkPerformancesType value) {
        this.workPerformances = value;
    }

    /**
     * Gets the value of the workSchedules property.
     * 
     * @return
     *     possible object is
     *     {@link WorkSchedulesType }
     *     
     */
    public WorkSchedulesType getWorkSchedules() {
        return workSchedules;
    }

    /**
     * Sets the value of the workSchedules property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkSchedulesType }
     *     
     */
    public void setWorkSchedules(WorkSchedulesType value) {
        this.workSchedules = value;
    }

    /**
     * Gets the value of the batchProductionRecord property.
     * 
     * @return
     *     possible object is
     *     {@link BatchProductionRecordType }
     *     
     */
    public BatchProductionRecordType getBatchProductionRecord() {
        return batchProductionRecord;
    }

    /**
     * Sets the value of the batchProductionRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchProductionRecordType }
     *     
     */
    public void setBatchProductionRecord(BatchProductionRecordType value) {
        this.batchProductionRecord = value;
    }

}
