//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 02:10:24 PM CST 
//


package org.mesa.xml.b2mml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BatchListEntryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BatchListEntryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/B2MML-V0600}IDType"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/B2MML-V0600}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="BatchListEntryType" type="{http://www.mesa.org/xml/B2MML-V0600}BatchListEntryTypeType"/>
 *         &lt;element name="Status" type="{http://www.mesa.org/xml/B2MML-V0600}BatchStatusType" minOccurs="0"/>
 *         &lt;element name="Mode" type="{http://www.mesa.org/xml/B2MML-V0600}ModeType" minOccurs="0"/>
 *         &lt;element name="ExternalID" type="{http://www.mesa.org/xml/B2MML-V0600}ExternalIDType" minOccurs="0"/>
 *         &lt;element name="RecipeID" type="{http://www.mesa.org/xml/B2MML-V0600}RecipeIDType" minOccurs="0"/>
 *         &lt;element name="RecipeVersion" type="{http://www.mesa.org/xml/B2MML-V0600}RecipeVersionType" minOccurs="0"/>
 *         &lt;element name="BatchID" type="{http://www.mesa.org/xml/B2MML-V0600}BatchIDType" minOccurs="0"/>
 *         &lt;element name="LotID" type="{http://www.mesa.org/xml/B2MML-V0600}LotIDType" minOccurs="0"/>
 *         &lt;element name="CampaignID" type="{http://www.mesa.org/xml/B2MML-V0600}CampaignIDType" minOccurs="0"/>
 *         &lt;element name="ProductID" type="{http://www.mesa.org/xml/B2MML-V0600}ProductIDType" minOccurs="0"/>
 *         &lt;element name="OrderID" type="{http://www.mesa.org/xml/B2MML-V0600}OrderIDType" minOccurs="0"/>
 *         &lt;element name="StartCondition" type="{http://www.mesa.org/xml/B2MML-V0600}StartConditionType" minOccurs="0"/>
 *         &lt;element name="RequestedStartTime" type="{http://www.mesa.org/xml/B2MML-V0600}RequestedStartTimeType" minOccurs="0"/>
 *         &lt;element name="ActualStartTime" type="{http://www.mesa.org/xml/B2MML-V0600}ActualStartTimeType" minOccurs="0"/>
 *         &lt;element name="RequestedEndTime" type="{http://www.mesa.org/xml/B2MML-V0600}RequestedEndTimeType" minOccurs="0"/>
 *         &lt;element name="ActualEndTime" type="{http://www.mesa.org/xml/B2MML-V0600}ActualEndTimeType" minOccurs="0"/>
 *         &lt;element name="BatchPriority" type="{http://www.mesa.org/xml/B2MML-V0600}BatchPriorityType" minOccurs="0"/>
 *         &lt;element name="RequestedBatchSize" type="{http://www.mesa.org/xml/B2MML-V0600}RequestedBatchSizeType" minOccurs="0"/>
 *         &lt;element name="ActualBatchSize" type="{http://www.mesa.org/xml/B2MML-V0600}ActualBatchSizeType" minOccurs="0"/>
 *         &lt;element name="UnitOfMeasure" type="{http://www.mesa.org/xml/B2MML-V0600}UnitOfMeasureType" minOccurs="0"/>
 *         &lt;element name="Note" type="{http://www.mesa.org/xml/B2MML-V0600}NoteType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Parameter" type="{http://www.mesa.org/xml/B2MML-V0600}BatchParameterType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="EquipmentID" type="{http://www.mesa.org/xml/B2MML-V0600}BatchEquipmentIDType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="EquipmentClassID" type="{http://www.mesa.org/xml/B2MML-V0600}BatchEquipmentClassIDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="ActualEquipmentID" type="{http://www.mesa.org/xml/B2MML-V0600}ActualEquipmentIDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="BatchListEntry" type="{http://www.mesa.org/xml/B2MML-V0600}BatchListEntryType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-V0600-AllExtensions}BatchListEntry" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BatchListEntryType", propOrder = {
    "id",
    "description",
    "batchListEntryType",
    "status",
    "mode",
    "externalID",
    "recipeID",
    "recipeVersion",
    "batchID",
    "lotID",
    "campaignID",
    "productID",
    "orderID",
    "startCondition",
    "requestedStartTime",
    "actualStartTime",
    "requestedEndTime",
    "actualEndTime",
    "batchPriority",
    "requestedBatchSize",
    "actualBatchSize",
    "unitOfMeasure",
    "note",
    "parameter",
    "equipmentIDOrEquipmentClassID",
    "actualEquipmentID",
    "batchListEntry"
})
public class BatchListEntryType {

    @XmlElement(name = "ID", required = true)
    protected IDType id;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "BatchListEntryType", required = true)
    protected BatchListEntryTypeType batchListEntryType;
    @XmlElement(name = "Status")
    protected BatchStatusType status;
    @XmlElement(name = "Mode")
    protected ModeType mode;
    @XmlElement(name = "ExternalID")
    protected ExternalIDType externalID;
    @XmlElement(name = "RecipeID")
    protected RecipeIDType recipeID;
    @XmlElement(name = "RecipeVersion")
    protected RecipeVersionType recipeVersion;
    @XmlElement(name = "BatchID")
    protected BatchIDType batchID;
    @XmlElement(name = "LotID")
    protected LotIDType lotID;
    @XmlElement(name = "CampaignID")
    protected CampaignIDType campaignID;
    @XmlElement(name = "ProductID")
    protected ProductIDType productID;
    @XmlElement(name = "OrderID")
    protected OrderIDType orderID;
    @XmlElement(name = "StartCondition")
    protected StartConditionType startCondition;
    @XmlElement(name = "RequestedStartTime")
    protected RequestedStartTimeType requestedStartTime;
    @XmlElement(name = "ActualStartTime")
    protected ActualStartTimeType actualStartTime;
    @XmlElement(name = "RequestedEndTime")
    protected RequestedEndTimeType requestedEndTime;
    @XmlElement(name = "ActualEndTime")
    protected ActualEndTimeType actualEndTime;
    @XmlElement(name = "BatchPriority")
    protected BatchPriorityType batchPriority;
    @XmlElement(name = "RequestedBatchSize")
    protected RequestedBatchSizeType requestedBatchSize;
    @XmlElement(name = "ActualBatchSize")
    protected ActualBatchSizeType actualBatchSize;
    @XmlElement(name = "UnitOfMeasure")
    protected UnitOfMeasureType unitOfMeasure;
    @XmlElement(name = "Note")
    protected List<NoteType> note;
    @XmlElement(name = "Parameter")
    protected List<BatchParameterType> parameter;
    @XmlElements({
        @XmlElement(name = "EquipmentID", type = BatchEquipmentIDType.class),
        @XmlElement(name = "EquipmentClassID", type = BatchEquipmentClassIDType.class)
    })
    protected List<Object> equipmentIDOrEquipmentClassID;
    @XmlElement(name = "ActualEquipmentID")
    protected List<ActualEquipmentIDType> actualEquipmentID;
    @XmlElement(name = "BatchListEntry")
    protected List<BatchListEntryType> batchListEntry;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setID(IDType value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the batchListEntryType property.
     * 
     * @return
     *     possible object is
     *     {@link BatchListEntryTypeType }
     *     
     */
    public BatchListEntryTypeType getBatchListEntryType() {
        return batchListEntryType;
    }

    /**
     * Sets the value of the batchListEntryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchListEntryTypeType }
     *     
     */
    public void setBatchListEntryType(BatchListEntryTypeType value) {
        this.batchListEntryType = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link BatchStatusType }
     *     
     */
    public BatchStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchStatusType }
     *     
     */
    public void setStatus(BatchStatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link ModeType }
     *     
     */
    public ModeType getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModeType }
     *     
     */
    public void setMode(ModeType value) {
        this.mode = value;
    }

    /**
     * Gets the value of the externalID property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalIDType }
     *     
     */
    public ExternalIDType getExternalID() {
        return externalID;
    }

    /**
     * Sets the value of the externalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalIDType }
     *     
     */
    public void setExternalID(ExternalIDType value) {
        this.externalID = value;
    }

    /**
     * Gets the value of the recipeID property.
     * 
     * @return
     *     possible object is
     *     {@link RecipeIDType }
     *     
     */
    public RecipeIDType getRecipeID() {
        return recipeID;
    }

    /**
     * Sets the value of the recipeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipeIDType }
     *     
     */
    public void setRecipeID(RecipeIDType value) {
        this.recipeID = value;
    }

    /**
     * Gets the value of the recipeVersion property.
     * 
     * @return
     *     possible object is
     *     {@link RecipeVersionType }
     *     
     */
    public RecipeVersionType getRecipeVersion() {
        return recipeVersion;
    }

    /**
     * Sets the value of the recipeVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipeVersionType }
     *     
     */
    public void setRecipeVersion(RecipeVersionType value) {
        this.recipeVersion = value;
    }

    /**
     * Gets the value of the batchID property.
     * 
     * @return
     *     possible object is
     *     {@link BatchIDType }
     *     
     */
    public BatchIDType getBatchID() {
        return batchID;
    }

    /**
     * Sets the value of the batchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchIDType }
     *     
     */
    public void setBatchID(BatchIDType value) {
        this.batchID = value;
    }

    /**
     * Gets the value of the lotID property.
     * 
     * @return
     *     possible object is
     *     {@link LotIDType }
     *     
     */
    public LotIDType getLotID() {
        return lotID;
    }

    /**
     * Sets the value of the lotID property.
     * 
     * @param value
     *     allowed object is
     *     {@link LotIDType }
     *     
     */
    public void setLotID(LotIDType value) {
        this.lotID = value;
    }

    /**
     * Gets the value of the campaignID property.
     * 
     * @return
     *     possible object is
     *     {@link CampaignIDType }
     *     
     */
    public CampaignIDType getCampaignID() {
        return campaignID;
    }

    /**
     * Sets the value of the campaignID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CampaignIDType }
     *     
     */
    public void setCampaignID(CampaignIDType value) {
        this.campaignID = value;
    }

    /**
     * Gets the value of the productID property.
     * 
     * @return
     *     possible object is
     *     {@link ProductIDType }
     *     
     */
    public ProductIDType getProductID() {
        return productID;
    }

    /**
     * Sets the value of the productID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductIDType }
     *     
     */
    public void setProductID(ProductIDType value) {
        this.productID = value;
    }

    /**
     * Gets the value of the orderID property.
     * 
     * @return
     *     possible object is
     *     {@link OrderIDType }
     *     
     */
    public OrderIDType getOrderID() {
        return orderID;
    }

    /**
     * Sets the value of the orderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderIDType }
     *     
     */
    public void setOrderID(OrderIDType value) {
        this.orderID = value;
    }

    /**
     * Gets the value of the startCondition property.
     * 
     * @return
     *     possible object is
     *     {@link StartConditionType }
     *     
     */
    public StartConditionType getStartCondition() {
        return startCondition;
    }

    /**
     * Sets the value of the startCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartConditionType }
     *     
     */
    public void setStartCondition(StartConditionType value) {
        this.startCondition = value;
    }

    /**
     * Gets the value of the requestedStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedStartTimeType }
     *     
     */
    public RequestedStartTimeType getRequestedStartTime() {
        return requestedStartTime;
    }

    /**
     * Sets the value of the requestedStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedStartTimeType }
     *     
     */
    public void setRequestedStartTime(RequestedStartTimeType value) {
        this.requestedStartTime = value;
    }

    /**
     * Gets the value of the actualStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link ActualStartTimeType }
     *     
     */
    public ActualStartTimeType getActualStartTime() {
        return actualStartTime;
    }

    /**
     * Sets the value of the actualStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualStartTimeType }
     *     
     */
    public void setActualStartTime(ActualStartTimeType value) {
        this.actualStartTime = value;
    }

    /**
     * Gets the value of the requestedEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedEndTimeType }
     *     
     */
    public RequestedEndTimeType getRequestedEndTime() {
        return requestedEndTime;
    }

    /**
     * Sets the value of the requestedEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedEndTimeType }
     *     
     */
    public void setRequestedEndTime(RequestedEndTimeType value) {
        this.requestedEndTime = value;
    }

    /**
     * Gets the value of the actualEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link ActualEndTimeType }
     *     
     */
    public ActualEndTimeType getActualEndTime() {
        return actualEndTime;
    }

    /**
     * Sets the value of the actualEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualEndTimeType }
     *     
     */
    public void setActualEndTime(ActualEndTimeType value) {
        this.actualEndTime = value;
    }

    /**
     * Gets the value of the batchPriority property.
     * 
     * @return
     *     possible object is
     *     {@link BatchPriorityType }
     *     
     */
    public BatchPriorityType getBatchPriority() {
        return batchPriority;
    }

    /**
     * Sets the value of the batchPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchPriorityType }
     *     
     */
    public void setBatchPriority(BatchPriorityType value) {
        this.batchPriority = value;
    }

    /**
     * Gets the value of the requestedBatchSize property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedBatchSizeType }
     *     
     */
    public RequestedBatchSizeType getRequestedBatchSize() {
        return requestedBatchSize;
    }

    /**
     * Sets the value of the requestedBatchSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedBatchSizeType }
     *     
     */
    public void setRequestedBatchSize(RequestedBatchSizeType value) {
        this.requestedBatchSize = value;
    }

    /**
     * Gets the value of the actualBatchSize property.
     * 
     * @return
     *     possible object is
     *     {@link ActualBatchSizeType }
     *     
     */
    public ActualBatchSizeType getActualBatchSize() {
        return actualBatchSize;
    }

    /**
     * Sets the value of the actualBatchSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualBatchSizeType }
     *     
     */
    public void setActualBatchSize(ActualBatchSizeType value) {
        this.actualBatchSize = value;
    }

    /**
     * Gets the value of the unitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link UnitOfMeasureType }
     *     
     */
    public UnitOfMeasureType getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitOfMeasureType }
     *     
     */
    public void setUnitOfMeasure(UnitOfMeasureType value) {
        this.unitOfMeasure = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoteType }
     * 
     * 
     */
    public List<NoteType> getNote() {
        if (note == null) {
            note = new ArrayList<NoteType>();
        }
        return this.note;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BatchParameterType }
     * 
     * 
     */
    public List<BatchParameterType> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<BatchParameterType>();
        }
        return this.parameter;
    }

    /**
     * Gets the value of the equipmentIDOrEquipmentClassID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentIDOrEquipmentClassID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentIDOrEquipmentClassID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BatchEquipmentIDType }
     * {@link BatchEquipmentClassIDType }
     * 
     * 
     */
    public List<Object> getEquipmentIDOrEquipmentClassID() {
        if (equipmentIDOrEquipmentClassID == null) {
            equipmentIDOrEquipmentClassID = new ArrayList<Object>();
        }
        return this.equipmentIDOrEquipmentClassID;
    }

    /**
     * Gets the value of the actualEquipmentID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actualEquipmentID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActualEquipmentID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActualEquipmentIDType }
     * 
     * 
     */
    public List<ActualEquipmentIDType> getActualEquipmentID() {
        if (actualEquipmentID == null) {
            actualEquipmentID = new ArrayList<ActualEquipmentIDType>();
        }
        return this.actualEquipmentID;
    }

    /**
     * Gets the value of the batchListEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the batchListEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBatchListEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BatchListEntryType }
     * 
     * 
     */
    public List<BatchListEntryType> getBatchListEntry() {
        if (batchListEntry == null) {
            batchListEntry = new ArrayList<BatchListEntryType>();
        }
        return this.batchListEntry;
    }

}
