//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 02:10:24 PM CST 
//


package org.mesa.xml.b2mml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FromIDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FromIDType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FromIDValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FromType" type="{http://www.mesa.org/xml/B2MML-V0600}FromTypeType"/>
 *         &lt;element name="IDScope" type="{http://www.mesa.org/xml/B2MML-V0600}IDScopeType"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-V0600-AllExtensions}FromID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FromIDType", propOrder = {
    "fromIDValue",
    "fromType",
    "idScope"
})
public class FromIDType {

    @XmlElement(name = "FromIDValue", required = true)
    protected String fromIDValue;
    @XmlElement(name = "FromType", required = true)
    protected FromTypeType fromType;
    @XmlElement(name = "IDScope", required = true)
    protected IDScopeType idScope;

    /**
     * Gets the value of the fromIDValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromIDValue() {
        return fromIDValue;
    }

    /**
     * Sets the value of the fromIDValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromIDValue(String value) {
        this.fromIDValue = value;
    }

    /**
     * Gets the value of the fromType property.
     * 
     * @return
     *     possible object is
     *     {@link FromTypeType }
     *     
     */
    public FromTypeType getFromType() {
        return fromType;
    }

    /**
     * Sets the value of the fromType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FromTypeType }
     *     
     */
    public void setFromType(FromTypeType value) {
        this.fromType = value;
    }

    /**
     * Gets the value of the idScope property.
     * 
     * @return
     *     possible object is
     *     {@link IDScopeType }
     *     
     */
    public IDScopeType getIDScope() {
        return idScope;
    }

    /**
     * Sets the value of the idScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDScopeType }
     *     
     */
    public void setIDScope(IDScopeType value) {
        this.idScope = value;
    }

}
