//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 02:11:12 PM CST 
//


package org.mesa.xml.b2mml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GRecipeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GRecipeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/B2MML-V0600}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GRecipeType" type="{http://www.mesa.org/xml/B2MML-V0600}GRecipeTypeType" minOccurs="0"/>
 *         &lt;element name="LifeCycleState" type="{http://www.mesa.org/xml/B2MML-V0600}LifeCycleStateType" minOccurs="0"/>
 *         &lt;element name="Header" type="{http://www.mesa.org/xml/B2MML-V0600}GRecipeHeaderType" minOccurs="0"/>
 *         &lt;element name="Formula" type="{http://www.mesa.org/xml/B2MML-V0600}GRecipeFormulaType" minOccurs="0"/>
 *         &lt;element name="ProcessProcedure" type="{http://www.mesa.org/xml/B2MML-V0600}ProcessElementType" minOccurs="0"/>
 *         &lt;element name="ResourceConstraint" type="{http://www.mesa.org/xml/B2MML-V0600}ResourceConstraintType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OtherInformation" type="{http://www.mesa.org/xml/B2MML-V0600}GROtherInformationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-V0600-AllExtensions}GRecipe" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GRecipeType", propOrder = {
    "id",
    "description",
    "gRecipeType",
    "lifeCycleState",
    "header",
    "formula",
    "processProcedure",
    "resourceConstraint",
    "otherInformation"
})
public class GRecipeType {

    @XmlElement(name = "ID")
    protected IdentifierType id;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "GRecipeType")
    protected GRecipeTypeType gRecipeType;
    @XmlElement(name = "LifeCycleState")
    protected LifeCycleStateType lifeCycleState;
    @XmlElement(name = "Header")
    protected GRecipeHeaderType header;
    @XmlElement(name = "Formula")
    protected GRecipeFormulaType formula;
    @XmlElement(name = "ProcessProcedure")
    protected ProcessElementType processProcedure;
    @XmlElement(name = "ResourceConstraint")
    protected List<ResourceConstraintType> resourceConstraint;
    @XmlElement(name = "OtherInformation")
    protected List<GROtherInformationType> otherInformation;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the gRecipeType property.
     * 
     * @return
     *     possible object is
     *     {@link GRecipeTypeType }
     *     
     */
    public GRecipeTypeType getGRecipeType() {
        return gRecipeType;
    }

    /**
     * Sets the value of the gRecipeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GRecipeTypeType }
     *     
     */
    public void setGRecipeType(GRecipeTypeType value) {
        this.gRecipeType = value;
    }

    /**
     * Gets the value of the lifeCycleState property.
     * 
     * @return
     *     possible object is
     *     {@link LifeCycleStateType }
     *     
     */
    public LifeCycleStateType getLifeCycleState() {
        return lifeCycleState;
    }

    /**
     * Sets the value of the lifeCycleState property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifeCycleStateType }
     *     
     */
    public void setLifeCycleState(LifeCycleStateType value) {
        this.lifeCycleState = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link GRecipeHeaderType }
     *     
     */
    public GRecipeHeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link GRecipeHeaderType }
     *     
     */
    public void setHeader(GRecipeHeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the formula property.
     * 
     * @return
     *     possible object is
     *     {@link GRecipeFormulaType }
     *     
     */
    public GRecipeFormulaType getFormula() {
        return formula;
    }

    /**
     * Sets the value of the formula property.
     * 
     * @param value
     *     allowed object is
     *     {@link GRecipeFormulaType }
     *     
     */
    public void setFormula(GRecipeFormulaType value) {
        this.formula = value;
    }

    /**
     * Gets the value of the processProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessElementType }
     *     
     */
    public ProcessElementType getProcessProcedure() {
        return processProcedure;
    }

    /**
     * Sets the value of the processProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessElementType }
     *     
     */
    public void setProcessProcedure(ProcessElementType value) {
        this.processProcedure = value;
    }

    /**
     * Gets the value of the resourceConstraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceConstraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceConstraintType }
     * 
     * 
     */
    public List<ResourceConstraintType> getResourceConstraint() {
        if (resourceConstraint == null) {
            resourceConstraint = new ArrayList<ResourceConstraintType>();
        }
        return this.resourceConstraint;
    }

    /**
     * Gets the value of the otherInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GROtherInformationType }
     * 
     * 
     */
    public List<GROtherInformationType> getOtherInformation() {
        if (otherInformation == null) {
            otherInformation = new ArrayList<GROtherInformationType>();
        }
        return this.otherInformation;
    }

}
