//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 02:11:12 PM CST 
//


package org.mesa.xml.b2mml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mesa.xml.b2mml package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CancelGRecipeInformation_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "CancelGRecipeInformation");
    private final static QName _ShowResourceConstraintLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "ShowResourceConstraintLibrary");
    private final static QName _ResourceConstraintLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "ResourceConstraintLibrary");
    private final static QName _AcknowledgeProcessElementLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "AcknowledgeProcessElementLibrary");
    private final static QName _ResourceConstraint_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "ResourceConstraint");
    private final static QName _GRecipe_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "GRecipe");
    private final static QName _SyncProcessElementLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "SyncProcessElementLibrary");
    private final static QName _GetProcessElementLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "GetProcessElementLibrary");
    private final static QName _ProcessElement_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "ProcessElement");
    private final static QName _ChangeGRecipeInformation_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "ChangeGRecipeInformation");
    private final static QName _GetResourceConstraintLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "GetResourceConstraintLibrary");
    private final static QName _ChangeResourceConstraintLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "ChangeResourceConstraintLibrary");
    private final static QName _ProcessGRecipeInformation_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "ProcessGRecipeInformation");
    private final static QName _ChangeProcessElementLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "ChangeProcessElementLibrary");
    private final static QName _SyncResourceConstraintLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "SyncResourceConstraintLibrary");
    private final static QName _ProcessProcessElementLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "ProcessProcessElementLibrary");
    private final static QName _RespondProcessElementLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "RespondProcessElementLibrary");
    private final static QName _SyncGRecipeInformation_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "SyncGRecipeInformation");
    private final static QName _AcknowledgeGRecipeInformation_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "AcknowledgeGRecipeInformation");
    private final static QName _GetGRecipeInformation_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "GetGRecipeInformation");
    private final static QName _CancelProcessElementLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "CancelProcessElementLibrary");
    private final static QName _GRecipeInformation_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "GRecipeInformation");
    private final static QName _ShowGRecipeInformation_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "ShowGRecipeInformation");
    private final static QName _CancelResourceConstraintLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "CancelResourceConstraintLibrary");
    private final static QName _ProcessResourceConstraintLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "ProcessResourceConstraintLibrary");
    private final static QName _AcknowledgeResourceConstraintLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "AcknowledgeResourceConstraintLibrary");
    private final static QName _ShowProcessElementLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "ShowProcessElementLibrary");
    private final static QName _RespondResourceConstraintLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "RespondResourceConstraintLibrary");
    private final static QName _ProcessElementLibrary_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "ProcessElementLibrary");
    private final static QName _RespondGRecipeInformation_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "RespondGRecipeInformation");
    private final static QName _ResultTypeUnitOfMeasure_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "UnitOfMeasure");
    private final static QName _ResultTypeDataType_QNAME = new QName("http://www.mesa.org/xml/B2MML-V0600", "DataType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mesa.xml.b2mml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProcessProcessElementLibraryType }
     * 
     */
    public ProcessProcessElementLibraryType createProcessProcessElementLibraryType() {
        return new ProcessProcessElementLibraryType();
    }

    /**
     * Create an instance of {@link SyncResourceConstraintLibraryType }
     * 
     */
    public SyncResourceConstraintLibraryType createSyncResourceConstraintLibraryType() {
        return new SyncResourceConstraintLibraryType();
    }

    /**
     * Create an instance of {@link ChangeProcessElementLibraryType }
     * 
     */
    public ChangeProcessElementLibraryType createChangeProcessElementLibraryType() {
        return new ChangeProcessElementLibraryType();
    }

    /**
     * Create an instance of {@link ChangeResourceConstraintLibraryType }
     * 
     */
    public ChangeResourceConstraintLibraryType createChangeResourceConstraintLibraryType() {
        return new ChangeResourceConstraintLibraryType();
    }

    /**
     * Create an instance of {@link GetResourceConstraintLibraryType }
     * 
     */
    public GetResourceConstraintLibraryType createGetResourceConstraintLibraryType() {
        return new GetResourceConstraintLibraryType();
    }

    /**
     * Create an instance of {@link ProcessGRecipeInformationType }
     * 
     */
    public ProcessGRecipeInformationType createProcessGRecipeInformationType() {
        return new ProcessGRecipeInformationType();
    }

    /**
     * Create an instance of {@link ChangeGRecipeInformationType }
     * 
     */
    public ChangeGRecipeInformationType createChangeGRecipeInformationType() {
        return new ChangeGRecipeInformationType();
    }

    /**
     * Create an instance of {@link GetProcessElementLibraryType }
     * 
     */
    public GetProcessElementLibraryType createGetProcessElementLibraryType() {
        return new GetProcessElementLibraryType();
    }

    /**
     * Create an instance of {@link SyncProcessElementLibraryType }
     * 
     */
    public SyncProcessElementLibraryType createSyncProcessElementLibraryType() {
        return new SyncProcessElementLibraryType();
    }

    /**
     * Create an instance of {@link AcknowledgeProcessElementLibraryType }
     * 
     */
    public AcknowledgeProcessElementLibraryType createAcknowledgeProcessElementLibraryType() {
        return new AcknowledgeProcessElementLibraryType();
    }

    /**
     * Create an instance of {@link ShowResourceConstraintLibraryType }
     * 
     */
    public ShowResourceConstraintLibraryType createShowResourceConstraintLibraryType() {
        return new ShowResourceConstraintLibraryType();
    }

    /**
     * Create an instance of {@link CancelGRecipeInformationType }
     * 
     */
    public CancelGRecipeInformationType createCancelGRecipeInformationType() {
        return new CancelGRecipeInformationType();
    }

    /**
     * Create an instance of {@link RespondGRecipeInformationType }
     * 
     */
    public RespondGRecipeInformationType createRespondGRecipeInformationType() {
        return new RespondGRecipeInformationType();
    }

    /**
     * Create an instance of {@link ShowProcessElementLibraryType }
     * 
     */
    public ShowProcessElementLibraryType createShowProcessElementLibraryType() {
        return new ShowProcessElementLibraryType();
    }

    /**
     * Create an instance of {@link AcknowledgeResourceConstraintLibraryType }
     * 
     */
    public AcknowledgeResourceConstraintLibraryType createAcknowledgeResourceConstraintLibraryType() {
        return new AcknowledgeResourceConstraintLibraryType();
    }

    /**
     * Create an instance of {@link RespondResourceConstraintLibraryType }
     * 
     */
    public RespondResourceConstraintLibraryType createRespondResourceConstraintLibraryType() {
        return new RespondResourceConstraintLibraryType();
    }

    /**
     * Create an instance of {@link ProcessResourceConstraintLibraryType }
     * 
     */
    public ProcessResourceConstraintLibraryType createProcessResourceConstraintLibraryType() {
        return new ProcessResourceConstraintLibraryType();
    }

    /**
     * Create an instance of {@link CancelResourceConstraintLibraryType }
     * 
     */
    public CancelResourceConstraintLibraryType createCancelResourceConstraintLibraryType() {
        return new CancelResourceConstraintLibraryType();
    }

    /**
     * Create an instance of {@link ShowGRecipeInformationType }
     * 
     */
    public ShowGRecipeInformationType createShowGRecipeInformationType() {
        return new ShowGRecipeInformationType();
    }

    /**
     * Create an instance of {@link CancelProcessElementLibraryType }
     * 
     */
    public CancelProcessElementLibraryType createCancelProcessElementLibraryType() {
        return new CancelProcessElementLibraryType();
    }

    /**
     * Create an instance of {@link GetGRecipeInformationType }
     * 
     */
    public GetGRecipeInformationType createGetGRecipeInformationType() {
        return new GetGRecipeInformationType();
    }

    /**
     * Create an instance of {@link AcknowledgeGRecipeInformationType }
     * 
     */
    public AcknowledgeGRecipeInformationType createAcknowledgeGRecipeInformationType() {
        return new AcknowledgeGRecipeInformationType();
    }

    /**
     * Create an instance of {@link SyncGRecipeInformationType }
     * 
     */
    public SyncGRecipeInformationType createSyncGRecipeInformationType() {
        return new SyncGRecipeInformationType();
    }

    /**
     * Create an instance of {@link RespondProcessElementLibraryType }
     * 
     */
    public RespondProcessElementLibraryType createRespondProcessElementLibraryType() {
        return new RespondProcessElementLibraryType();
    }

    /**
     * Create an instance of {@link GRecipeInformationType }
     * 
     */
    public GRecipeInformationType createGRecipeInformationType() {
        return new GRecipeInformationType();
    }

    /**
     * Create an instance of {@link ProcessElementLibraryType }
     * 
     */
    public ProcessElementLibraryType createProcessElementLibraryType() {
        return new ProcessElementLibraryType();
    }

    /**
     * Create an instance of {@link ResourceConstraintLibraryType }
     * 
     */
    public ResourceConstraintLibraryType createResourceConstraintLibraryType() {
        return new ResourceConstraintLibraryType();
    }

    /**
     * Create an instance of {@link ResourceConstraintType }
     * 
     */
    public ResourceConstraintType createResourceConstraintType() {
        return new ResourceConstraintType();
    }

    /**
     * Create an instance of {@link GRecipeType }
     * 
     */
    public GRecipeType createGRecipeType() {
        return new GRecipeType();
    }

    /**
     * Create an instance of {@link ProcessElementType }
     * 
     */
    public ProcessElementType createProcessElementType() {
        return new ProcessElementType();
    }

    /**
     * Create an instance of {@link ProductProductionRuleType }
     * 
     */
    public ProductProductionRuleType createProductProductionRuleType() {
        return new ProductProductionRuleType();
    }

    /**
     * Create an instance of {@link TransChangeStatusType }
     * 
     */
    public TransChangeStatusType createTransChangeStatusType() {
        return new TransChangeStatusType();
    }

    /**
     * Create an instance of {@link OpMaterialCapabilityType }
     * 
     */
    public OpMaterialCapabilityType createOpMaterialCapabilityType() {
        return new OpMaterialCapabilityType();
    }

    /**
     * Create an instance of {@link CertificateOfAnalysisReferenceType }
     * 
     */
    public CertificateOfAnalysisReferenceType createCertificateOfAnalysisReferenceType() {
        return new CertificateOfAnalysisReferenceType();
    }

    /**
     * Create an instance of {@link PhysicalAssetActualIDType }
     * 
     */
    public PhysicalAssetActualIDType createPhysicalAssetActualIDType() {
        return new PhysicalAssetActualIDType();
    }

    /**
     * Create an instance of {@link OpEquipmentSpecificationPropertyType }
     * 
     */
    public OpEquipmentSpecificationPropertyType createOpEquipmentSpecificationPropertyType() {
        return new OpEquipmentSpecificationPropertyType();
    }

    /**
     * Create an instance of {@link DependencyType }
     * 
     */
    public DependencyType createDependencyType() {
        return new DependencyType();
    }

    /**
     * Create an instance of {@link EquipmentElementLevel1Type }
     * 
     */
    public EquipmentElementLevel1Type createEquipmentElementLevel1Type() {
        return new EquipmentElementLevel1Type();
    }

    /**
     * Create an instance of {@link OpPhysicalAssetSpecificationPropertyType }
     * 
     */
    public OpPhysicalAssetSpecificationPropertyType createOpPhysicalAssetSpecificationPropertyType() {
        return new OpPhysicalAssetSpecificationPropertyType();
    }

    /**
     * Create an instance of {@link PlannedStartTimeType }
     * 
     */
    public PlannedStartTimeType createPlannedStartTimeType() {
        return new PlannedStartTimeType();
    }

    /**
     * Create an instance of {@link ProductSegmentIDType }
     * 
     */
    public ProductSegmentIDType createProductSegmentIDType() {
        return new ProductSegmentIDType();
    }

    /**
     * Create an instance of {@link OpEquipmentCapabilityType }
     * 
     */
    public OpEquipmentCapabilityType createOpEquipmentCapabilityType() {
        return new OpEquipmentCapabilityType();
    }

    /**
     * Create an instance of {@link JobOrderCommandRuleType }
     * 
     */
    public JobOrderCommandRuleType createJobOrderCommandRuleType() {
        return new JobOrderCommandRuleType();
    }

    /**
     * Create an instance of {@link ExpirationTimeType }
     * 
     */
    public ExpirationTimeType createExpirationTimeType() {
        return new ExpirationTimeType();
    }

    /**
     * Create an instance of {@link TransSyncType }
     * 
     */
    public TransSyncType createTransSyncType() {
        return new TransSyncType();
    }

    /**
     * Create an instance of {@link AssemblyType1Type }
     * 
     */
    public AssemblyType1Type createAssemblyType1Type() {
        return new AssemblyType1Type();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link AmountType }
     * 
     */
    public AmountType createAmountType() {
        return new AmountType();
    }

    /**
     * Create an instance of {@link RequiredByRequestedSegmentResponseType }
     * 
     */
    public RequiredByRequestedSegmentResponseType createRequiredByRequestedSegmentResponseType() {
        return new RequiredByRequestedSegmentResponseType();
    }

    /**
     * Create an instance of {@link EquipmentUseType }
     * 
     */
    public EquipmentUseType createEquipmentUseType() {
        return new EquipmentUseType();
    }

    /**
     * Create an instance of {@link NumericType }
     * 
     */
    public NumericType createNumericType() {
        return new NumericType();
    }

    /**
     * Create an instance of {@link ProcessElementType1Type }
     * 
     */
    public ProcessElementType1Type createProcessElementType1Type() {
        return new ProcessElementType1Type();
    }

    /**
     * Create an instance of {@link ProcessElementParameterType1Type }
     * 
     */
    public ProcessElementParameterType1Type createProcessElementParameterType1Type() {
        return new ProcessElementParameterType1Type();
    }

    /**
     * Create an instance of {@link PersonnelUseType }
     * 
     */
    public PersonnelUseType createPersonnelUseType() {
        return new PersonnelUseType();
    }

    /**
     * Create an instance of {@link CauseType }
     * 
     */
    public CauseType createCauseType() {
        return new CauseType();
    }

    /**
     * Create an instance of {@link TransGetType }
     * 
     */
    public TransGetType createTransGetType() {
        return new TransGetType();
    }

    /**
     * Create an instance of {@link ActualFinishTimeType }
     * 
     */
    public ActualFinishTimeType createActualFinishTimeType() {
        return new ActualFinishTimeType();
    }

    /**
     * Create an instance of {@link ProcessSegmentIDType }
     * 
     */
    public ProcessSegmentIDType createProcessSegmentIDType() {
        return new ProcessSegmentIDType();
    }

    /**
     * Create an instance of {@link TransStateChangeType }
     * 
     */
    public TransStateChangeType createTransStateChangeType() {
        return new TransStateChangeType();
    }

    /**
     * Create an instance of {@link ProcessElementParameterTypeType }
     * 
     */
    public ProcessElementParameterTypeType createProcessElementParameterTypeType() {
        return new ProcessElementParameterTypeType();
    }

    /**
     * Create an instance of {@link ReasonType }
     * 
     */
    public ReasonType createReasonType() {
        return new ReasonType();
    }

    /**
     * Create an instance of {@link OpPhysicalAssetRequirementType }
     * 
     */
    public OpPhysicalAssetRequirementType createOpPhysicalAssetRequirementType() {
        return new OpPhysicalAssetRequirementType();
    }

    /**
     * Create an instance of {@link OpEquipmentSpecificationType }
     * 
     */
    public OpEquipmentSpecificationType createOpEquipmentSpecificationType() {
        return new OpEquipmentSpecificationType();
    }

    /**
     * Create an instance of {@link TransSignatureType }
     * 
     */
    public TransSignatureType createTransSignatureType() {
        return new TransSignatureType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link ValueStringType }
     * 
     */
    public ValueStringType createValueStringType() {
        return new ValueStringType();
    }

    /**
     * Create an instance of {@link OpPhysicalAssetCapabilityType }
     * 
     */
    public OpPhysicalAssetCapabilityType createOpPhysicalAssetCapabilityType() {
        return new OpPhysicalAssetCapabilityType();
    }

    /**
     * Create an instance of {@link VersionType }
     * 
     */
    public VersionType createVersionType() {
        return new VersionType();
    }

    /**
     * Create an instance of {@link PhysicalAssetIDType }
     * 
     */
    public PhysicalAssetIDType createPhysicalAssetIDType() {
        return new PhysicalAssetIDType();
    }

    /**
     * Create an instance of {@link EndTimeType }
     * 
     */
    public EndTimeType createEndTimeType() {
        return new EndTimeType();
    }

    /**
     * Create an instance of {@link WorkRequestIDType }
     * 
     */
    public WorkRequestIDType createWorkRequestIDType() {
        return new WorkRequestIDType();
    }

    /**
     * Create an instance of {@link TransSenderType }
     * 
     */
    public TransSenderType createTransSenderType() {
        return new TransSenderType();
    }

    /**
     * Create an instance of {@link OtherDependencyType }
     * 
     */
    public OtherDependencyType createOtherDependencyType() {
        return new OtherDependencyType();
    }

    /**
     * Create an instance of {@link AnyGenericValueType }
     * 
     */
    public AnyGenericValueType createAnyGenericValueType() {
        return new AnyGenericValueType();
    }

    /**
     * Create an instance of {@link OpPersonnelRequirementPropertyType }
     * 
     */
    public OpPersonnelRequirementPropertyType createOpPersonnelRequirementPropertyType() {
        return new OpPersonnelRequirementPropertyType();
    }

    /**
     * Create an instance of {@link RequestedCompletionDateType }
     * 
     */
    public RequestedCompletionDateType createRequestedCompletionDateType() {
        return new RequestedCompletionDateType();
    }

    /**
     * Create an instance of {@link QualificationTestSpecificationIDType }
     * 
     */
    public QualificationTestSpecificationIDType createQualificationTestSpecificationIDType() {
        return new QualificationTestSpecificationIDType();
    }

    /**
     * Create an instance of {@link GRecipeMaterialType }
     * 
     */
    public GRecipeMaterialType createGRecipeMaterialType() {
        return new GRecipeMaterialType();
    }

    /**
     * Create an instance of {@link WorkTypeType }
     * 
     */
    public WorkTypeType createWorkTypeType() {
        return new WorkTypeType();
    }

    /**
     * Create an instance of {@link ResourceReferenceType1Type }
     * 
     */
    public ResourceReferenceType1Type createResourceReferenceType1Type() {
        return new ResourceReferenceType1Type();
    }

    /**
     * Create an instance of {@link LatestEndTimeType }
     * 
     */
    public LatestEndTimeType createLatestEndTimeType() {
        return new LatestEndTimeType();
    }

    /**
     * Create an instance of {@link PhysicalAssetClassIDType }
     * 
     */
    public PhysicalAssetClassIDType createPhysicalAssetClassIDType() {
        return new PhysicalAssetClassIDType();
    }

    /**
     * Create an instance of {@link TransChangeType }
     * 
     */
    public TransChangeType createTransChangeType() {
        return new TransChangeType();
    }

    /**
     * Create an instance of {@link LifeCycleStateType }
     * 
     */
    public LifeCycleStateType createLifeCycleStateType() {
        return new LifeCycleStateType();
    }

    /**
     * Create an instance of {@link OpPhysicalAssetRequirementPropertyType }
     * 
     */
    public OpPhysicalAssetRequirementPropertyType createOpPhysicalAssetRequirementPropertyType() {
        return new OpPhysicalAssetRequirementPropertyType();
    }

    /**
     * Create an instance of {@link TransActionCriteriaType }
     * 
     */
    public TransActionCriteriaType createTransActionCriteriaType() {
        return new TransActionCriteriaType();
    }

    /**
     * Create an instance of {@link RequestedPriorityType }
     * 
     */
    public RequestedPriorityType createRequestedPriorityType() {
        return new RequestedPriorityType();
    }

    /**
     * Create an instance of {@link DirectedLinkType }
     * 
     */
    public DirectedLinkType createDirectedLinkType() {
        return new DirectedLinkType();
    }

    /**
     * Create an instance of {@link RelationshipForm1Type }
     * 
     */
    public RelationshipForm1Type createRelationshipForm1Type() {
        return new RelationshipForm1Type();
    }

    /**
     * Create an instance of {@link EquipmentElementLevelType }
     * 
     */
    public EquipmentElementLevelType createEquipmentElementLevelType() {
        return new EquipmentElementLevelType();
    }

    /**
     * Create an instance of {@link MaterialsTypeType }
     * 
     */
    public MaterialsTypeType createMaterialsTypeType() {
        return new MaterialsTypeType();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link OpMaterialRequirementPropertyType }
     * 
     */
    public OpMaterialRequirementPropertyType createOpMaterialRequirementPropertyType() {
        return new OpMaterialRequirementPropertyType();
    }

    /**
     * Create an instance of {@link QuantityType }
     * 
     */
    public QuantityType createQuantityType() {
        return new QuantityType();
    }

    /**
     * Create an instance of {@link JobOrderDispatchStatusType }
     * 
     */
    public JobOrderDispatchStatusType createJobOrderDispatchStatusType() {
        return new JobOrderDispatchStatusType();
    }

    /**
     * Create an instance of {@link MaterialClassIDType }
     * 
     */
    public MaterialClassIDType createMaterialClassIDType() {
        return new MaterialClassIDType();
    }

    /**
     * Create an instance of {@link ResourceIDType }
     * 
     */
    public ResourceIDType createResourceIDType() {
        return new ResourceIDType();
    }

    /**
     * Create an instance of {@link RequiredByRequestedSegmentResponse1Type }
     * 
     */
    public RequiredByRequestedSegmentResponse1Type createRequiredByRequestedSegmentResponse1Type() {
        return new RequiredByRequestedSegmentResponse1Type();
    }

    /**
     * Create an instance of {@link ResourceConstraintPropertyType }
     * 
     */
    public ResourceConstraintPropertyType createResourceConstraintPropertyType() {
        return new ResourceConstraintPropertyType();
    }

    /**
     * Create an instance of {@link BillOfResourcesIDType }
     * 
     */
    public BillOfResourcesIDType createBillOfResourcesIDType() {
        return new BillOfResourcesIDType();
    }

    /**
     * Create an instance of {@link EquipmentAssetMappingType }
     * 
     */
    public EquipmentAssetMappingType createEquipmentAssetMappingType() {
        return new EquipmentAssetMappingType();
    }

    /**
     * Create an instance of {@link Dependency1Type }
     * 
     */
    public Dependency1Type createDependency1Type() {
        return new Dependency1Type();
    }

    /**
     * Create an instance of {@link MeasureType }
     * 
     */
    public MeasureType createMeasureType() {
        return new MeasureType();
    }

    /**
     * Create an instance of {@link TransShowType }
     * 
     */
    public TransShowType createTransShowType() {
        return new TransShowType();
    }

    /**
     * Create an instance of {@link TestDateTimeType }
     * 
     */
    public TestDateTimeType createTestDateTimeType() {
        return new TestDateTimeType();
    }

    /**
     * Create an instance of {@link SequenceOrderType1Type }
     * 
     */
    public SequenceOrderType1Type createSequenceOrderType1Type() {
        return new SequenceOrderType1Type();
    }

    /**
     * Create an instance of {@link HeaderPropertyType }
     * 
     */
    public HeaderPropertyType createHeaderPropertyType() {
        return new HeaderPropertyType();
    }

    /**
     * Create an instance of {@link ProcessElementTypeType }
     * 
     */
    public ProcessElementTypeType createProcessElementTypeType() {
        return new ProcessElementTypeType();
    }

    /**
     * Create an instance of {@link BillOfMaterialIDType }
     * 
     */
    public BillOfMaterialIDType createBillOfMaterialIDType() {
        return new BillOfMaterialIDType();
    }

    /**
     * Create an instance of {@link TestResultType }
     * 
     */
    public TestResultType createTestResultType() {
        return new TestResultType();
    }

    /**
     * Create an instance of {@link OpEquipmentCapabilityPropertyType }
     * 
     */
    public OpEquipmentCapabilityPropertyType createOpEquipmentCapabilityPropertyType() {
        return new OpEquipmentCapabilityPropertyType();
    }

    /**
     * Create an instance of {@link RelationshipFormType }
     * 
     */
    public RelationshipFormType createRelationshipFormType() {
        return new RelationshipFormType();
    }

    /**
     * Create an instance of {@link RequestStateType }
     * 
     */
    public RequestStateType createRequestStateType() {
        return new RequestStateType();
    }

    /**
     * Create an instance of {@link PlannedFinishTimeType }
     * 
     */
    public PlannedFinishTimeType createPlannedFinishTimeType() {
        return new PlannedFinishTimeType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link StorageHierarchyScopeType }
     * 
     */
    public StorageHierarchyScopeType createStorageHierarchyScopeType() {
        return new StorageHierarchyScopeType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link WorkScheduleIDType }
     * 
     */
    public WorkScheduleIDType createWorkScheduleIDType() {
        return new WorkScheduleIDType();
    }

    /**
     * Create an instance of {@link DataType1Type }
     * 
     */
    public DataType1Type createDataType1Type() {
        return new DataType1Type();
    }

    /**
     * Create an instance of {@link UnitOfMeasureType }
     * 
     */
    public UnitOfMeasureType createUnitOfMeasureType() {
        return new UnitOfMeasureType();
    }

    /**
     * Create an instance of {@link TransResponseCriteriaType }
     * 
     */
    public TransResponseCriteriaType createTransResponseCriteriaType() {
        return new TransResponseCriteriaType();
    }

    /**
     * Create an instance of {@link WorkType1Type }
     * 
     */
    public WorkType1Type createWorkType1Type() {
        return new WorkType1Type();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link OpPersonnelCapabilityPropertyType }
     * 
     */
    public OpPersonnelCapabilityPropertyType createOpPersonnelCapabilityPropertyType() {
        return new OpPersonnelCapabilityPropertyType();
    }

    /**
     * Create an instance of {@link TransApplicationAreaType }
     * 
     */
    public TransApplicationAreaType createTransApplicationAreaType() {
        return new TransApplicationAreaType();
    }

    /**
     * Create an instance of {@link CapabilityType1Type }
     * 
     */
    public CapabilityType1Type createCapabilityType1Type() {
        return new CapabilityType1Type();
    }

    /**
     * Create an instance of {@link EquipmentCapabilityTestSpecificationIDType }
     * 
     */
    public EquipmentCapabilityTestSpecificationIDType createEquipmentCapabilityTestSpecificationIDType() {
        return new EquipmentCapabilityTestSpecificationIDType();
    }

    /**
     * Create an instance of {@link ProcedureChartElementType1Type }
     * 
     */
    public ProcedureChartElementType1Type createProcedureChartElementType1Type() {
        return new ProcedureChartElementType1Type();
    }

    /**
     * Create an instance of {@link PersonnelClassIDType }
     * 
     */
    public PersonnelClassIDType createPersonnelClassIDType() {
        return new PersonnelClassIDType();
    }

    /**
     * Create an instance of {@link OperationsTypeType }
     * 
     */
    public OperationsTypeType createOperationsTypeType() {
        return new OperationsTypeType();
    }

    /**
     * Create an instance of {@link RequestState1Type }
     * 
     */
    public RequestState1Type createRequestState1Type() {
        return new RequestState1Type();
    }

    /**
     * Create an instance of {@link MaterialLotIDType }
     * 
     */
    public MaterialLotIDType createMaterialLotIDType() {
        return new MaterialLotIDType();
    }

    /**
     * Create an instance of {@link OperationsSegmentIDType }
     * 
     */
    public OperationsSegmentIDType createOperationsSegmentIDType() {
        return new OperationsSegmentIDType();
    }

    /**
     * Create an instance of {@link OpEquipmentRequirementPropertyType }
     * 
     */
    public OpEquipmentRequirementPropertyType createOpEquipmentRequirementPropertyType() {
        return new OpEquipmentRequirementPropertyType();
    }

    /**
     * Create an instance of {@link MaterialCapabilityIDType }
     * 
     */
    public MaterialCapabilityIDType createMaterialCapabilityIDType() {
        return new MaterialCapabilityIDType();
    }

    /**
     * Create an instance of {@link BinaryObjectType }
     * 
     */
    public BinaryObjectType createBinaryObjectType() {
        return new BinaryObjectType();
    }

    /**
     * Create an instance of {@link PhysicalAssetCapabilityTestSpecificationIDType }
     * 
     */
    public PhysicalAssetCapabilityTestSpecificationIDType createPhysicalAssetCapabilityTestSpecificationIDType() {
        return new PhysicalAssetCapabilityTestSpecificationIDType();
    }

    /**
     * Create an instance of {@link ResponseState1Type }
     * 
     */
    public ResponseState1Type createResponseState1Type() {
        return new ResponseState1Type();
    }

    /**
     * Create an instance of {@link ProcedureChartElementTypeType }
     * 
     */
    public ProcedureChartElementTypeType createProcedureChartElementTypeType() {
        return new ProcedureChartElementTypeType();
    }

    /**
     * Create an instance of {@link ProductionScheduleIDType }
     * 
     */
    public ProductionScheduleIDType createProductionScheduleIDType() {
        return new ProductionScheduleIDType();
    }

    /**
     * Create an instance of {@link OperationsDefinitionIDType }
     * 
     */
    public OperationsDefinitionIDType createOperationsDefinitionIDType() {
        return new OperationsDefinitionIDType();
    }

    /**
     * Create an instance of {@link ResourceReferenceTypeType }
     * 
     */
    public ResourceReferenceTypeType createResourceReferenceTypeType() {
        return new ResourceReferenceTypeType();
    }

    /**
     * Create an instance of {@link GRecipeType1Type }
     * 
     */
    public GRecipeType1Type createGRecipeType1Type() {
        return new GRecipeType1Type();
    }

    /**
     * Create an instance of {@link EquipmentIDType }
     * 
     */
    public EquipmentIDType createEquipmentIDType() {
        return new EquipmentIDType();
    }

    /**
     * Create an instance of {@link AssemblyTypeType }
     * 
     */
    public AssemblyTypeType createAssemblyTypeType() {
        return new AssemblyTypeType();
    }

    /**
     * Create an instance of {@link TransUserAreaType }
     * 
     */
    public TransUserAreaType createTransUserAreaType() {
        return new TransUserAreaType();
    }

    /**
     * Create an instance of {@link MaterialSpecificationIDType }
     * 
     */
    public MaterialSpecificationIDType createMaterialSpecificationIDType() {
        return new MaterialSpecificationIDType();
    }

    /**
     * Create an instance of {@link ProductionRequestIDType }
     * 
     */
    public ProductionRequestIDType createProductionRequestIDType() {
        return new ProductionRequestIDType();
    }

    /**
     * Create an instance of {@link MaterialActualIDType }
     * 
     */
    public MaterialActualIDType createMaterialActualIDType() {
        return new MaterialActualIDType();
    }

    /**
     * Create an instance of {@link ConfidenceFactorType }
     * 
     */
    public ConfidenceFactorType createConfidenceFactorType() {
        return new ConfidenceFactorType();
    }

    /**
     * Create an instance of {@link GROtherInformationType }
     * 
     */
    public GROtherInformationType createGROtherInformationType() {
        return new GROtherInformationType();
    }

    /**
     * Create an instance of {@link StatusTimeType }
     * 
     */
    public StatusTimeType createStatusTimeType() {
        return new StatusTimeType();
    }

    /**
     * Create an instance of {@link ProcedureChartElementType }
     * 
     */
    public ProcedureChartElementType createProcedureChartElementType() {
        return new ProcedureChartElementType();
    }

    /**
     * Create an instance of {@link PersonNameType }
     * 
     */
    public PersonNameType createPersonNameType() {
        return new PersonNameType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link AssemblyRelationship1Type }
     * 
     */
    public AssemblyRelationship1Type createAssemblyRelationship1Type() {
        return new AssemblyRelationship1Type();
    }

    /**
     * Create an instance of {@link MaterialsType1Type }
     * 
     */
    public MaterialsType1Type createMaterialsType1Type() {
        return new MaterialsType1Type();
    }

    /**
     * Create an instance of {@link MaterialDefinitionIDType }
     * 
     */
    public MaterialDefinitionIDType createMaterialDefinitionIDType() {
        return new MaterialDefinitionIDType();
    }

    /**
     * Create an instance of {@link StartTimeType }
     * 
     */
    public StartTimeType createStartTimeType() {
        return new StartTimeType();
    }

    /**
     * Create an instance of {@link ProcessElementParameterType }
     * 
     */
    public ProcessElementParameterType createProcessElementParameterType() {
        return new ProcessElementParameterType();
    }

    /**
     * Create an instance of {@link OpEquipmentRequirementType }
     * 
     */
    public OpEquipmentRequirementType createOpEquipmentRequirementType() {
        return new OpEquipmentRequirementType();
    }

    /**
     * Create an instance of {@link GRecipeHeaderType }
     * 
     */
    public GRecipeHeaderType createGRecipeHeaderType() {
        return new GRecipeHeaderType();
    }

    /**
     * Create an instance of {@link OpMaterialSpecificationPropertyType }
     * 
     */
    public OpMaterialSpecificationPropertyType createOpMaterialSpecificationPropertyType() {
        return new OpMaterialSpecificationPropertyType();
    }

    /**
     * Create an instance of {@link MaterialRequirementIDType }
     * 
     */
    public MaterialRequirementIDType createMaterialRequirementIDType() {
        return new MaterialRequirementIDType();
    }

    /**
     * Create an instance of {@link OpMaterialSpecificationType }
     * 
     */
    public OpMaterialSpecificationType createOpMaterialSpecificationType() {
        return new OpMaterialSpecificationType();
    }

    /**
     * Create an instance of {@link ProductProductionRuleIDType }
     * 
     */
    public ProductProductionRuleIDType createProductProductionRuleIDType() {
        return new ProductProductionRuleIDType();
    }

    /**
     * Create an instance of {@link ActualStartTimeType }
     * 
     */
    public ActualStartTimeType createActualStartTimeType() {
        return new ActualStartTimeType();
    }

    /**
     * Create an instance of {@link MaterialUse1Type }
     * 
     */
    public MaterialUse1Type createMaterialUse1Type() {
        return new MaterialUse1Type();
    }

    /**
     * Create an instance of {@link PriorityType }
     * 
     */
    public PriorityType createPriorityType() {
        return new PriorityType();
    }

    /**
     * Create an instance of {@link OpPersonnelSpecificationPropertyType }
     * 
     */
    public OpPersonnelSpecificationPropertyType createOpPersonnelSpecificationPropertyType() {
        return new OpPersonnelSpecificationPropertyType();
    }

    /**
     * Create an instance of {@link OpMaterialCapabilityPropertyType }
     * 
     */
    public OpMaterialCapabilityPropertyType createOpMaterialCapabilityPropertyType() {
        return new OpMaterialCapabilityPropertyType();
    }

    /**
     * Create an instance of {@link OpMaterialRequirementType }
     * 
     */
    public OpMaterialRequirementType createOpMaterialRequirementType() {
        return new OpMaterialRequirementType();
    }

    /**
     * Create an instance of {@link TransAcknowledgeType }
     * 
     */
    public TransAcknowledgeType createTransAcknowledgeType() {
        return new TransAcknowledgeType();
    }

    /**
     * Create an instance of {@link ResponseStateType }
     * 
     */
    public ResponseStateType createResponseStateType() {
        return new ResponseStateType();
    }

    /**
     * Create an instance of {@link CorrectionType }
     * 
     */
    public CorrectionType createCorrectionType() {
        return new CorrectionType();
    }

    /**
     * Create an instance of {@link HierarchyScopeType }
     * 
     */
    public HierarchyScopeType createHierarchyScopeType() {
        return new HierarchyScopeType();
    }

    /**
     * Create an instance of {@link ManufacturingBillIDType }
     * 
     */
    public ManufacturingBillIDType createManufacturingBillIDType() {
        return new ManufacturingBillIDType();
    }

    /**
     * Create an instance of {@link SegmentDependencyType }
     * 
     */
    public SegmentDependencyType createSegmentDependencyType() {
        return new SegmentDependencyType();
    }

    /**
     * Create an instance of {@link TransProcessType }
     * 
     */
    public TransProcessType createTransProcessType() {
        return new TransProcessType();
    }

    /**
     * Create an instance of {@link PersonIDType }
     * 
     */
    public PersonIDType createPersonIDType() {
        return new PersonIDType();
    }

    /**
     * Create an instance of {@link MaterialSubLotIDType }
     * 
     */
    public MaterialSubLotIDType createMaterialSubLotIDType() {
        return new MaterialSubLotIDType();
    }

    /**
     * Create an instance of {@link ConstraintTypeType }
     * 
     */
    public ConstraintTypeType createConstraintTypeType() {
        return new ConstraintTypeType();
    }

    /**
     * Create an instance of {@link OpPersonnelRequirementType }
     * 
     */
    public OpPersonnelRequirementType createOpPersonnelRequirementType() {
        return new OpPersonnelRequirementType();
    }

    /**
     * Create an instance of {@link OpPersonnelSpecificationType }
     * 
     */
    public OpPersonnelSpecificationType createOpPersonnelSpecificationType() {
        return new OpPersonnelSpecificationType();
    }

    /**
     * Create an instance of {@link EquipmentClassIDType }
     * 
     */
    public EquipmentClassIDType createEquipmentClassIDType() {
        return new EquipmentClassIDType();
    }

    /**
     * Create an instance of {@link RelationshipType1Type }
     * 
     */
    public RelationshipType1Type createRelationshipType1Type() {
        return new RelationshipType1Type();
    }

    /**
     * Create an instance of {@link OpPhysicalAssetCapabilityPropertyType }
     * 
     */
    public OpPhysicalAssetCapabilityPropertyType createOpPhysicalAssetCapabilityPropertyType() {
        return new OpPhysicalAssetCapabilityPropertyType();
    }

    /**
     * Create an instance of {@link TransCancelType }
     * 
     */
    public TransCancelType createTransCancelType() {
        return new TransCancelType();
    }

    /**
     * Create an instance of {@link OperationsRequestIDType }
     * 
     */
    public OperationsRequestIDType createOperationsRequestIDType() {
        return new OperationsRequestIDType();
    }

    /**
     * Create an instance of {@link TransRespondType }
     * 
     */
    public TransRespondType createTransRespondType() {
        return new TransRespondType();
    }

    /**
     * Create an instance of {@link SequenceOrderType }
     * 
     */
    public SequenceOrderType createSequenceOrderType() {
        return new SequenceOrderType();
    }

    /**
     * Create an instance of {@link PhysicalAssetUseType }
     * 
     */
    public PhysicalAssetUseType createPhysicalAssetUseType() {
        return new PhysicalAssetUseType();
    }

    /**
     * Create an instance of {@link TransConfirmationCodeType }
     * 
     */
    public TransConfirmationCodeType createTransConfirmationCodeType() {
        return new TransConfirmationCodeType();
    }

    /**
     * Create an instance of {@link PropertyIDType }
     * 
     */
    public PropertyIDType createPropertyIDType() {
        return new PropertyIDType();
    }

    /**
     * Create an instance of {@link ResultType }
     * 
     */
    public ResultType createResultType() {
        return new ResultType();
    }

    /**
     * Create an instance of {@link GRecipeTypeType }
     * 
     */
    public GRecipeTypeType createGRecipeTypeType() {
        return new GRecipeTypeType();
    }

    /**
     * Create an instance of {@link GRecipeFormulaType }
     * 
     */
    public GRecipeFormulaType createGRecipeFormulaType() {
        return new GRecipeFormulaType();
    }

    /**
     * Create an instance of {@link DateTimeType }
     * 
     */
    public DateTimeType createDateTimeType() {
        return new DateTimeType();
    }

    /**
     * Create an instance of {@link TransExpressionType }
     * 
     */
    public TransExpressionType createTransExpressionType() {
        return new TransExpressionType();
    }

    /**
     * Create an instance of {@link JobOrderCommandType }
     * 
     */
    public JobOrderCommandType createJobOrderCommandType() {
        return new JobOrderCommandType();
    }

    /**
     * Create an instance of {@link OpPersonnelCapabilityType }
     * 
     */
    public OpPersonnelCapabilityType createOpPersonnelCapabilityType() {
        return new OpPersonnelCapabilityType();
    }

    /**
     * Create an instance of {@link TransReceiverType }
     * 
     */
    public TransReceiverType createTransReceiverType() {
        return new TransReceiverType();
    }

    /**
     * Create an instance of {@link OpPhysicalAssetSpecificationType }
     * 
     */
    public OpPhysicalAssetSpecificationType createOpPhysicalAssetSpecificationType() {
        return new OpPhysicalAssetSpecificationType();
    }

    /**
     * Create an instance of {@link OperationsType1Type }
     * 
     */
    public OperationsType1Type createOperationsType1Type() {
        return new OperationsType1Type();
    }

    /**
     * Create an instance of {@link MaterialTestSpecificationIDType }
     * 
     */
    public MaterialTestSpecificationIDType createMaterialTestSpecificationIDType() {
        return new MaterialTestSpecificationIDType();
    }

    /**
     * Create an instance of {@link TransExpression1Type }
     * 
     */
    public TransExpression1Type createTransExpression1Type() {
        return new TransExpression1Type();
    }

    /**
     * Create an instance of {@link ParameterIDType }
     * 
     */
    public ParameterIDType createParameterIDType() {
        return new ParameterIDType();
    }

    /**
     * Create an instance of {@link QuantityStringType }
     * 
     */
    public QuantityStringType createQuantityStringType() {
        return new QuantityStringType();
    }

    /**
     * Create an instance of {@link JobOrderCommand1Type }
     * 
     */
    public JobOrderCommand1Type createJobOrderCommand1Type() {
        return new JobOrderCommand1Type();
    }

    /**
     * Create an instance of {@link ResourcesType }
     * 
     */
    public ResourcesType createResourcesType() {
        return new ResourcesType();
    }

    /**
     * Create an instance of {@link TransConfirmType }
     * 
     */
    public TransConfirmType createTransConfirmType() {
        return new TransConfirmType();
    }

    /**
     * Create an instance of {@link EarliestStartTimeType }
     * 
     */
    public EarliestStartTimeType createEarliestStartTimeType() {
        return new EarliestStartTimeType();
    }

    /**
     * Create an instance of {@link RelationshipTypeType }
     * 
     */
    public RelationshipTypeType createRelationshipTypeType() {
        return new RelationshipTypeType();
    }

    /**
     * Create an instance of {@link PublishedDateType }
     * 
     */
    public PublishedDateType createPublishedDateType() {
        return new PublishedDateType();
    }

    /**
     * Create an instance of {@link QuantityValueType }
     * 
     */
    public QuantityValueType createQuantityValueType() {
        return new QuantityValueType();
    }

    /**
     * Create an instance of {@link MaterialUseType }
     * 
     */
    public MaterialUseType createMaterialUseType() {
        return new MaterialUseType();
    }

    /**
     * Create an instance of {@link StorageLocationType }
     * 
     */
    public StorageLocationType createStorageLocationType() {
        return new StorageLocationType();
    }

    /**
     * Create an instance of {@link CapabilityTypeType }
     * 
     */
    public CapabilityTypeType createCapabilityTypeType() {
        return new CapabilityTypeType();
    }

    /**
     * Create an instance of {@link ValueType }
     * 
     */
    public ValueType createValueType() {
        return new ValueType();
    }

    /**
     * Create an instance of {@link GRecipeMaterialsType }
     * 
     */
    public GRecipeMaterialsType createGRecipeMaterialsType() {
        return new GRecipeMaterialsType();
    }

    /**
     * Create an instance of {@link DataTypeType }
     * 
     */
    public DataTypeType createDataTypeType() {
        return new DataTypeType();
    }

    /**
     * Create an instance of {@link BillOfMaterialsIDType }
     * 
     */
    public BillOfMaterialsIDType createBillOfMaterialsIDType() {
        return new BillOfMaterialsIDType();
    }

    /**
     * Create an instance of {@link AssemblyRelationshipType }
     * 
     */
    public AssemblyRelationshipType createAssemblyRelationshipType() {
        return new AssemblyRelationshipType();
    }

    /**
     * Create an instance of {@link OperationsScheduleIDType }
     * 
     */
    public OperationsScheduleIDType createOperationsScheduleIDType() {
        return new OperationsScheduleIDType();
    }

    /**
     * Create an instance of {@link ActualEndTimeType }
     * 
     */
    public ActualEndTimeType createActualEndTimeType() {
        return new ActualEndTimeType();
    }

    /**
     * Create an instance of {@link ResourceNetworkConnectionIDType }
     * 
     */
    public ResourceNetworkConnectionIDType createResourceNetworkConnectionIDType() {
        return new ResourceNetworkConnectionIDType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link ProblemType }
     * 
     */
    public ProblemType createProblemType() {
        return new ProblemType();
    }

    /**
     * Create an instance of {@link LifeCycleStateType1Type }
     * 
     */
    public LifeCycleStateType1Type createLifeCycleStateType1Type() {
        return new LifeCycleStateType1Type();
    }

    /**
     * Create an instance of {@link ConstraintType1Type }
     * 
     */
    public ConstraintType1Type createConstraintType1Type() {
        return new ConstraintType1Type();
    }

    /**
     * Create an instance of {@link ProcessProcessElementLibraryType.DataArea }
     * 
     */
    public ProcessProcessElementLibraryType.DataArea createProcessProcessElementLibraryTypeDataArea() {
        return new ProcessProcessElementLibraryType.DataArea();
    }

    /**
     * Create an instance of {@link SyncResourceConstraintLibraryType.DataArea }
     * 
     */
    public SyncResourceConstraintLibraryType.DataArea createSyncResourceConstraintLibraryTypeDataArea() {
        return new SyncResourceConstraintLibraryType.DataArea();
    }

    /**
     * Create an instance of {@link ChangeProcessElementLibraryType.DataArea }
     * 
     */
    public ChangeProcessElementLibraryType.DataArea createChangeProcessElementLibraryTypeDataArea() {
        return new ChangeProcessElementLibraryType.DataArea();
    }

    /**
     * Create an instance of {@link ChangeResourceConstraintLibraryType.DataArea }
     * 
     */
    public ChangeResourceConstraintLibraryType.DataArea createChangeResourceConstraintLibraryTypeDataArea() {
        return new ChangeResourceConstraintLibraryType.DataArea();
    }

    /**
     * Create an instance of {@link GetResourceConstraintLibraryType.DataArea }
     * 
     */
    public GetResourceConstraintLibraryType.DataArea createGetResourceConstraintLibraryTypeDataArea() {
        return new GetResourceConstraintLibraryType.DataArea();
    }

    /**
     * Create an instance of {@link ProcessGRecipeInformationType.DataArea }
     * 
     */
    public ProcessGRecipeInformationType.DataArea createProcessGRecipeInformationTypeDataArea() {
        return new ProcessGRecipeInformationType.DataArea();
    }

    /**
     * Create an instance of {@link ChangeGRecipeInformationType.DataArea }
     * 
     */
    public ChangeGRecipeInformationType.DataArea createChangeGRecipeInformationTypeDataArea() {
        return new ChangeGRecipeInformationType.DataArea();
    }

    /**
     * Create an instance of {@link GetProcessElementLibraryType.DataArea }
     * 
     */
    public GetProcessElementLibraryType.DataArea createGetProcessElementLibraryTypeDataArea() {
        return new GetProcessElementLibraryType.DataArea();
    }

    /**
     * Create an instance of {@link SyncProcessElementLibraryType.DataArea }
     * 
     */
    public SyncProcessElementLibraryType.DataArea createSyncProcessElementLibraryTypeDataArea() {
        return new SyncProcessElementLibraryType.DataArea();
    }

    /**
     * Create an instance of {@link AcknowledgeProcessElementLibraryType.DataArea }
     * 
     */
    public AcknowledgeProcessElementLibraryType.DataArea createAcknowledgeProcessElementLibraryTypeDataArea() {
        return new AcknowledgeProcessElementLibraryType.DataArea();
    }

    /**
     * Create an instance of {@link ShowResourceConstraintLibraryType.DataArea }
     * 
     */
    public ShowResourceConstraintLibraryType.DataArea createShowResourceConstraintLibraryTypeDataArea() {
        return new ShowResourceConstraintLibraryType.DataArea();
    }

    /**
     * Create an instance of {@link CancelGRecipeInformationType.DataArea }
     * 
     */
    public CancelGRecipeInformationType.DataArea createCancelGRecipeInformationTypeDataArea() {
        return new CancelGRecipeInformationType.DataArea();
    }

    /**
     * Create an instance of {@link RespondGRecipeInformationType.DataArea }
     * 
     */
    public RespondGRecipeInformationType.DataArea createRespondGRecipeInformationTypeDataArea() {
        return new RespondGRecipeInformationType.DataArea();
    }

    /**
     * Create an instance of {@link ShowProcessElementLibraryType.DataArea }
     * 
     */
    public ShowProcessElementLibraryType.DataArea createShowProcessElementLibraryTypeDataArea() {
        return new ShowProcessElementLibraryType.DataArea();
    }

    /**
     * Create an instance of {@link AcknowledgeResourceConstraintLibraryType.DataArea }
     * 
     */
    public AcknowledgeResourceConstraintLibraryType.DataArea createAcknowledgeResourceConstraintLibraryTypeDataArea() {
        return new AcknowledgeResourceConstraintLibraryType.DataArea();
    }

    /**
     * Create an instance of {@link RespondResourceConstraintLibraryType.DataArea }
     * 
     */
    public RespondResourceConstraintLibraryType.DataArea createRespondResourceConstraintLibraryTypeDataArea() {
        return new RespondResourceConstraintLibraryType.DataArea();
    }

    /**
     * Create an instance of {@link ProcessResourceConstraintLibraryType.DataArea }
     * 
     */
    public ProcessResourceConstraintLibraryType.DataArea createProcessResourceConstraintLibraryTypeDataArea() {
        return new ProcessResourceConstraintLibraryType.DataArea();
    }

    /**
     * Create an instance of {@link CancelResourceConstraintLibraryType.DataArea }
     * 
     */
    public CancelResourceConstraintLibraryType.DataArea createCancelResourceConstraintLibraryTypeDataArea() {
        return new CancelResourceConstraintLibraryType.DataArea();
    }

    /**
     * Create an instance of {@link ShowGRecipeInformationType.DataArea }
     * 
     */
    public ShowGRecipeInformationType.DataArea createShowGRecipeInformationTypeDataArea() {
        return new ShowGRecipeInformationType.DataArea();
    }

    /**
     * Create an instance of {@link CancelProcessElementLibraryType.DataArea }
     * 
     */
    public CancelProcessElementLibraryType.DataArea createCancelProcessElementLibraryTypeDataArea() {
        return new CancelProcessElementLibraryType.DataArea();
    }

    /**
     * Create an instance of {@link GetGRecipeInformationType.DataArea }
     * 
     */
    public GetGRecipeInformationType.DataArea createGetGRecipeInformationTypeDataArea() {
        return new GetGRecipeInformationType.DataArea();
    }

    /**
     * Create an instance of {@link AcknowledgeGRecipeInformationType.DataArea }
     * 
     */
    public AcknowledgeGRecipeInformationType.DataArea createAcknowledgeGRecipeInformationTypeDataArea() {
        return new AcknowledgeGRecipeInformationType.DataArea();
    }

    /**
     * Create an instance of {@link SyncGRecipeInformationType.DataArea }
     * 
     */
    public SyncGRecipeInformationType.DataArea createSyncGRecipeInformationTypeDataArea() {
        return new SyncGRecipeInformationType.DataArea();
    }

    /**
     * Create an instance of {@link RespondProcessElementLibraryType.DataArea }
     * 
     */
    public RespondProcessElementLibraryType.DataArea createRespondProcessElementLibraryTypeDataArea() {
        return new RespondProcessElementLibraryType.DataArea();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelGRecipeInformationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "CancelGRecipeInformation")
    public JAXBElement<CancelGRecipeInformationType> createCancelGRecipeInformation(CancelGRecipeInformationType value) {
        return new JAXBElement<CancelGRecipeInformationType>(_CancelGRecipeInformation_QNAME, CancelGRecipeInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowResourceConstraintLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "ShowResourceConstraintLibrary")
    public JAXBElement<ShowResourceConstraintLibraryType> createShowResourceConstraintLibrary(ShowResourceConstraintLibraryType value) {
        return new JAXBElement<ShowResourceConstraintLibraryType>(_ShowResourceConstraintLibrary_QNAME, ShowResourceConstraintLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceConstraintLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "ResourceConstraintLibrary")
    public JAXBElement<ResourceConstraintLibraryType> createResourceConstraintLibrary(ResourceConstraintLibraryType value) {
        return new JAXBElement<ResourceConstraintLibraryType>(_ResourceConstraintLibrary_QNAME, ResourceConstraintLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcknowledgeProcessElementLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "AcknowledgeProcessElementLibrary")
    public JAXBElement<AcknowledgeProcessElementLibraryType> createAcknowledgeProcessElementLibrary(AcknowledgeProcessElementLibraryType value) {
        return new JAXBElement<AcknowledgeProcessElementLibraryType>(_AcknowledgeProcessElementLibrary_QNAME, AcknowledgeProcessElementLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceConstraintType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "ResourceConstraint")
    public JAXBElement<ResourceConstraintType> createResourceConstraint(ResourceConstraintType value) {
        return new JAXBElement<ResourceConstraintType>(_ResourceConstraint_QNAME, ResourceConstraintType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GRecipeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "GRecipe")
    public JAXBElement<GRecipeType> createGRecipe(GRecipeType value) {
        return new JAXBElement<GRecipeType>(_GRecipe_QNAME, GRecipeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SyncProcessElementLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "SyncProcessElementLibrary")
    public JAXBElement<SyncProcessElementLibraryType> createSyncProcessElementLibrary(SyncProcessElementLibraryType value) {
        return new JAXBElement<SyncProcessElementLibraryType>(_SyncProcessElementLibrary_QNAME, SyncProcessElementLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProcessElementLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "GetProcessElementLibrary")
    public JAXBElement<GetProcessElementLibraryType> createGetProcessElementLibrary(GetProcessElementLibraryType value) {
        return new JAXBElement<GetProcessElementLibraryType>(_GetProcessElementLibrary_QNAME, GetProcessElementLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "ProcessElement")
    public JAXBElement<ProcessElementType> createProcessElement(ProcessElementType value) {
        return new JAXBElement<ProcessElementType>(_ProcessElement_QNAME, ProcessElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangeGRecipeInformationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "ChangeGRecipeInformation")
    public JAXBElement<ChangeGRecipeInformationType> createChangeGRecipeInformation(ChangeGRecipeInformationType value) {
        return new JAXBElement<ChangeGRecipeInformationType>(_ChangeGRecipeInformation_QNAME, ChangeGRecipeInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetResourceConstraintLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "GetResourceConstraintLibrary")
    public JAXBElement<GetResourceConstraintLibraryType> createGetResourceConstraintLibrary(GetResourceConstraintLibraryType value) {
        return new JAXBElement<GetResourceConstraintLibraryType>(_GetResourceConstraintLibrary_QNAME, GetResourceConstraintLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangeResourceConstraintLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "ChangeResourceConstraintLibrary")
    public JAXBElement<ChangeResourceConstraintLibraryType> createChangeResourceConstraintLibrary(ChangeResourceConstraintLibraryType value) {
        return new JAXBElement<ChangeResourceConstraintLibraryType>(_ChangeResourceConstraintLibrary_QNAME, ChangeResourceConstraintLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessGRecipeInformationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "ProcessGRecipeInformation")
    public JAXBElement<ProcessGRecipeInformationType> createProcessGRecipeInformation(ProcessGRecipeInformationType value) {
        return new JAXBElement<ProcessGRecipeInformationType>(_ProcessGRecipeInformation_QNAME, ProcessGRecipeInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangeProcessElementLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "ChangeProcessElementLibrary")
    public JAXBElement<ChangeProcessElementLibraryType> createChangeProcessElementLibrary(ChangeProcessElementLibraryType value) {
        return new JAXBElement<ChangeProcessElementLibraryType>(_ChangeProcessElementLibrary_QNAME, ChangeProcessElementLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SyncResourceConstraintLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "SyncResourceConstraintLibrary")
    public JAXBElement<SyncResourceConstraintLibraryType> createSyncResourceConstraintLibrary(SyncResourceConstraintLibraryType value) {
        return new JAXBElement<SyncResourceConstraintLibraryType>(_SyncResourceConstraintLibrary_QNAME, SyncResourceConstraintLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessProcessElementLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "ProcessProcessElementLibrary")
    public JAXBElement<ProcessProcessElementLibraryType> createProcessProcessElementLibrary(ProcessProcessElementLibraryType value) {
        return new JAXBElement<ProcessProcessElementLibraryType>(_ProcessProcessElementLibrary_QNAME, ProcessProcessElementLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RespondProcessElementLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "RespondProcessElementLibrary")
    public JAXBElement<RespondProcessElementLibraryType> createRespondProcessElementLibrary(RespondProcessElementLibraryType value) {
        return new JAXBElement<RespondProcessElementLibraryType>(_RespondProcessElementLibrary_QNAME, RespondProcessElementLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SyncGRecipeInformationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "SyncGRecipeInformation")
    public JAXBElement<SyncGRecipeInformationType> createSyncGRecipeInformation(SyncGRecipeInformationType value) {
        return new JAXBElement<SyncGRecipeInformationType>(_SyncGRecipeInformation_QNAME, SyncGRecipeInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcknowledgeGRecipeInformationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "AcknowledgeGRecipeInformation")
    public JAXBElement<AcknowledgeGRecipeInformationType> createAcknowledgeGRecipeInformation(AcknowledgeGRecipeInformationType value) {
        return new JAXBElement<AcknowledgeGRecipeInformationType>(_AcknowledgeGRecipeInformation_QNAME, AcknowledgeGRecipeInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetGRecipeInformationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "GetGRecipeInformation")
    public JAXBElement<GetGRecipeInformationType> createGetGRecipeInformation(GetGRecipeInformationType value) {
        return new JAXBElement<GetGRecipeInformationType>(_GetGRecipeInformation_QNAME, GetGRecipeInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelProcessElementLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "CancelProcessElementLibrary")
    public JAXBElement<CancelProcessElementLibraryType> createCancelProcessElementLibrary(CancelProcessElementLibraryType value) {
        return new JAXBElement<CancelProcessElementLibraryType>(_CancelProcessElementLibrary_QNAME, CancelProcessElementLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GRecipeInformationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "GRecipeInformation")
    public JAXBElement<GRecipeInformationType> createGRecipeInformation(GRecipeInformationType value) {
        return new JAXBElement<GRecipeInformationType>(_GRecipeInformation_QNAME, GRecipeInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowGRecipeInformationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "ShowGRecipeInformation")
    public JAXBElement<ShowGRecipeInformationType> createShowGRecipeInformation(ShowGRecipeInformationType value) {
        return new JAXBElement<ShowGRecipeInformationType>(_ShowGRecipeInformation_QNAME, ShowGRecipeInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelResourceConstraintLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "CancelResourceConstraintLibrary")
    public JAXBElement<CancelResourceConstraintLibraryType> createCancelResourceConstraintLibrary(CancelResourceConstraintLibraryType value) {
        return new JAXBElement<CancelResourceConstraintLibraryType>(_CancelResourceConstraintLibrary_QNAME, CancelResourceConstraintLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessResourceConstraintLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "ProcessResourceConstraintLibrary")
    public JAXBElement<ProcessResourceConstraintLibraryType> createProcessResourceConstraintLibrary(ProcessResourceConstraintLibraryType value) {
        return new JAXBElement<ProcessResourceConstraintLibraryType>(_ProcessResourceConstraintLibrary_QNAME, ProcessResourceConstraintLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcknowledgeResourceConstraintLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "AcknowledgeResourceConstraintLibrary")
    public JAXBElement<AcknowledgeResourceConstraintLibraryType> createAcknowledgeResourceConstraintLibrary(AcknowledgeResourceConstraintLibraryType value) {
        return new JAXBElement<AcknowledgeResourceConstraintLibraryType>(_AcknowledgeResourceConstraintLibrary_QNAME, AcknowledgeResourceConstraintLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowProcessElementLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "ShowProcessElementLibrary")
    public JAXBElement<ShowProcessElementLibraryType> createShowProcessElementLibrary(ShowProcessElementLibraryType value) {
        return new JAXBElement<ShowProcessElementLibraryType>(_ShowProcessElementLibrary_QNAME, ShowProcessElementLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RespondResourceConstraintLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "RespondResourceConstraintLibrary")
    public JAXBElement<RespondResourceConstraintLibraryType> createRespondResourceConstraintLibrary(RespondResourceConstraintLibraryType value) {
        return new JAXBElement<RespondResourceConstraintLibraryType>(_RespondResourceConstraintLibrary_QNAME, RespondResourceConstraintLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessElementLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "ProcessElementLibrary")
    public JAXBElement<ProcessElementLibraryType> createProcessElementLibrary(ProcessElementLibraryType value) {
        return new JAXBElement<ProcessElementLibraryType>(_ProcessElementLibrary_QNAME, ProcessElementLibraryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RespondGRecipeInformationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "RespondGRecipeInformation")
    public JAXBElement<RespondGRecipeInformationType> createRespondGRecipeInformation(RespondGRecipeInformationType value) {
        return new JAXBElement<RespondGRecipeInformationType>(_RespondGRecipeInformation_QNAME, RespondGRecipeInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnitOfMeasureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "UnitOfMeasure", scope = ResultType.class)
    public JAXBElement<UnitOfMeasureType> createResultTypeUnitOfMeasure(UnitOfMeasureType value) {
        return new JAXBElement<UnitOfMeasureType>(_ResultTypeUnitOfMeasure_QNAME, UnitOfMeasureType.class, ResultType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "DataType", scope = ResultType.class)
    public JAXBElement<DataTypeType> createResultTypeDataType(DataTypeType value) {
        return new JAXBElement<DataTypeType>(_ResultTypeDataType_QNAME, DataTypeType.class, ResultType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnitOfMeasureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "UnitOfMeasure", scope = QuantityValueType.class)
    public JAXBElement<UnitOfMeasureType> createQuantityValueTypeUnitOfMeasure(UnitOfMeasureType value) {
        return new JAXBElement<UnitOfMeasureType>(_ResultTypeUnitOfMeasure_QNAME, UnitOfMeasureType.class, QuantityValueType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "DataType", scope = QuantityValueType.class)
    public JAXBElement<DataTypeType> createQuantityValueTypeDataType(DataTypeType value) {
        return new JAXBElement<DataTypeType>(_ResultTypeDataType_QNAME, DataTypeType.class, QuantityValueType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnitOfMeasureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "UnitOfMeasure", scope = ValueType.class)
    public JAXBElement<UnitOfMeasureType> createValueTypeUnitOfMeasure(UnitOfMeasureType value) {
        return new JAXBElement<UnitOfMeasureType>(_ResultTypeUnitOfMeasure_QNAME, UnitOfMeasureType.class, ValueType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/B2MML-V0600", name = "DataType", scope = ValueType.class)
    public JAXBElement<DataTypeType> createValueTypeDataType(DataTypeType value) {
        return new JAXBElement<DataTypeType>(_ResultTypeDataType_QNAME, DataTypeType.class, ValueType.class, value);
    }

}
