//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 02:10:24 PM CST 
//


package org.mesa.xml.b2mml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OpSegmentResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpSegmentResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/B2MML-V0600}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="HierarchyScope" type="{http://www.mesa.org/xml/B2MML-V0600}HierarchyScopeType" minOccurs="0"/>
 *         &lt;element name="OperationsType" type="{http://www.mesa.org/xml/B2MML-V0600}OperationsTypeType" minOccurs="0"/>
 *         &lt;element name="ProcessSegmentID" type="{http://www.mesa.org/xml/B2MML-V0600}ProcessSegmentIDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ActualStartTime" type="{http://www.mesa.org/xml/B2MML-V0600}ActualStartTimeType" minOccurs="0"/>
 *         &lt;element name="ActualEndTime" type="{http://www.mesa.org/xml/B2MML-V0600}ActualEndTimeType" minOccurs="0"/>
 *         &lt;element name="OperationsDefinitionID" type="{http://www.mesa.org/xml/B2MML-V0600}OperationsDefinitionIDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SegmentState" type="{http://www.mesa.org/xml/B2MML-V0600}ResponseStateType" minOccurs="0"/>
 *         &lt;element name="SegmentData" type="{http://www.mesa.org/xml/B2MML-V0600}OpSegmentDataType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PersonnelActual" type="{http://www.mesa.org/xml/B2MML-V0600}OpPersonnelActualType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EquipmentActual" type="{http://www.mesa.org/xml/B2MML-V0600}OpEquipmentActualType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PhysicalAssetActual" type="{http://www.mesa.org/xml/B2MML-V0600}OpPhysicalAssetActualType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MaterialActual" type="{http://www.mesa.org/xml/B2MML-V0600}OpMaterialActualType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SegmentResponse" type="{http://www.mesa.org/xml/B2MML-V0600}OpSegmentResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RequiredByRequestedSegmentResponse" type="{http://www.mesa.org/xml/B2MML-V0600}RequiredByRequestedSegmentResponseType" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-V0600-AllExtensions}OpSegmentResponse" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpSegmentResponseType", propOrder = {
    "id",
    "description",
    "hierarchyScope",
    "operationsType",
    "processSegmentID",
    "actualStartTime",
    "actualEndTime",
    "operationsDefinitionID",
    "segmentState",
    "segmentData",
    "personnelActual",
    "equipmentActual",
    "physicalAssetActual",
    "materialActual",
    "segmentResponse",
    "requiredByRequestedSegmentResponse"
})
public class OpSegmentResponseType {

    @XmlElement(name = "ID")
    protected IdentifierType id;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "HierarchyScope")
    protected HierarchyScopeType hierarchyScope;
    @XmlElement(name = "OperationsType")
    protected OperationsTypeType operationsType;
    @XmlElement(name = "ProcessSegmentID")
    protected List<ProcessSegmentIDType> processSegmentID;
    @XmlElement(name = "ActualStartTime")
    protected ActualStartTimeType actualStartTime;
    @XmlElement(name = "ActualEndTime")
    protected ActualEndTimeType actualEndTime;
    @XmlElement(name = "OperationsDefinitionID")
    protected List<OperationsDefinitionIDType> operationsDefinitionID;
    @XmlElement(name = "SegmentState")
    protected ResponseStateType segmentState;
    @XmlElement(name = "SegmentData")
    protected List<OpSegmentDataType> segmentData;
    @XmlElement(name = "PersonnelActual")
    protected List<OpPersonnelActualType> personnelActual;
    @XmlElement(name = "EquipmentActual")
    protected List<OpEquipmentActualType> equipmentActual;
    @XmlElement(name = "PhysicalAssetActual")
    protected List<OpPhysicalAssetActualType> physicalAssetActual;
    @XmlElement(name = "MaterialActual")
    protected List<OpMaterialActualType> materialActual;
    @XmlElement(name = "SegmentResponse")
    protected List<OpSegmentResponseType> segmentResponse;
    @XmlElement(name = "RequiredByRequestedSegmentResponse")
    protected RequiredByRequestedSegmentResponseType requiredByRequestedSegmentResponse;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the hierarchyScope property.
     * 
     * @return
     *     possible object is
     *     {@link HierarchyScopeType }
     *     
     */
    public HierarchyScopeType getHierarchyScope() {
        return hierarchyScope;
    }

    /**
     * Sets the value of the hierarchyScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link HierarchyScopeType }
     *     
     */
    public void setHierarchyScope(HierarchyScopeType value) {
        this.hierarchyScope = value;
    }

    /**
     * Gets the value of the operationsType property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsTypeType }
     *     
     */
    public OperationsTypeType getOperationsType() {
        return operationsType;
    }

    /**
     * Sets the value of the operationsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsTypeType }
     *     
     */
    public void setOperationsType(OperationsTypeType value) {
        this.operationsType = value;
    }

    /**
     * Gets the value of the processSegmentID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processSegmentID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessSegmentID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessSegmentIDType }
     * 
     * 
     */
    public List<ProcessSegmentIDType> getProcessSegmentID() {
        if (processSegmentID == null) {
            processSegmentID = new ArrayList<ProcessSegmentIDType>();
        }
        return this.processSegmentID;
    }

    /**
     * Gets the value of the actualStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link ActualStartTimeType }
     *     
     */
    public ActualStartTimeType getActualStartTime() {
        return actualStartTime;
    }

    /**
     * Sets the value of the actualStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualStartTimeType }
     *     
     */
    public void setActualStartTime(ActualStartTimeType value) {
        this.actualStartTime = value;
    }

    /**
     * Gets the value of the actualEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link ActualEndTimeType }
     *     
     */
    public ActualEndTimeType getActualEndTime() {
        return actualEndTime;
    }

    /**
     * Sets the value of the actualEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualEndTimeType }
     *     
     */
    public void setActualEndTime(ActualEndTimeType value) {
        this.actualEndTime = value;
    }

    /**
     * Gets the value of the operationsDefinitionID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operationsDefinitionID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperationsDefinitionID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperationsDefinitionIDType }
     * 
     * 
     */
    public List<OperationsDefinitionIDType> getOperationsDefinitionID() {
        if (operationsDefinitionID == null) {
            operationsDefinitionID = new ArrayList<OperationsDefinitionIDType>();
        }
        return this.operationsDefinitionID;
    }

    /**
     * Gets the value of the segmentState property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseStateType }
     *     
     */
    public ResponseStateType getSegmentState() {
        return segmentState;
    }

    /**
     * Sets the value of the segmentState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseStateType }
     *     
     */
    public void setSegmentState(ResponseStateType value) {
        this.segmentState = value;
    }

    /**
     * Gets the value of the segmentData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the segmentData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegmentData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpSegmentDataType }
     * 
     * 
     */
    public List<OpSegmentDataType> getSegmentData() {
        if (segmentData == null) {
            segmentData = new ArrayList<OpSegmentDataType>();
        }
        return this.segmentData;
    }

    /**
     * Gets the value of the personnelActual property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personnelActual property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonnelActual().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpPersonnelActualType }
     * 
     * 
     */
    public List<OpPersonnelActualType> getPersonnelActual() {
        if (personnelActual == null) {
            personnelActual = new ArrayList<OpPersonnelActualType>();
        }
        return this.personnelActual;
    }

    /**
     * Gets the value of the equipmentActual property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentActual property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentActual().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpEquipmentActualType }
     * 
     * 
     */
    public List<OpEquipmentActualType> getEquipmentActual() {
        if (equipmentActual == null) {
            equipmentActual = new ArrayList<OpEquipmentActualType>();
        }
        return this.equipmentActual;
    }

    /**
     * Gets the value of the physicalAssetActual property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physicalAssetActual property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysicalAssetActual().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpPhysicalAssetActualType }
     * 
     * 
     */
    public List<OpPhysicalAssetActualType> getPhysicalAssetActual() {
        if (physicalAssetActual == null) {
            physicalAssetActual = new ArrayList<OpPhysicalAssetActualType>();
        }
        return this.physicalAssetActual;
    }

    /**
     * Gets the value of the materialActual property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the materialActual property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaterialActual().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpMaterialActualType }
     * 
     * 
     */
    public List<OpMaterialActualType> getMaterialActual() {
        if (materialActual == null) {
            materialActual = new ArrayList<OpMaterialActualType>();
        }
        return this.materialActual;
    }

    /**
     * Gets the value of the segmentResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the segmentResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegmentResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpSegmentResponseType }
     * 
     * 
     */
    public List<OpSegmentResponseType> getSegmentResponse() {
        if (segmentResponse == null) {
            segmentResponse = new ArrayList<OpSegmentResponseType>();
        }
        return this.segmentResponse;
    }

    /**
     * Gets the value of the requiredByRequestedSegmentResponse property.
     * 
     * @return
     *     possible object is
     *     {@link RequiredByRequestedSegmentResponseType }
     *     
     */
    public RequiredByRequestedSegmentResponseType getRequiredByRequestedSegmentResponse() {
        return requiredByRequestedSegmentResponse;
    }

    /**
     * Sets the value of the requiredByRequestedSegmentResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequiredByRequestedSegmentResponseType }
     *     
     */
    public void setRequiredByRequestedSegmentResponse(RequiredByRequestedSegmentResponseType value) {
        this.requiredByRequestedSegmentResponse = value;
    }

}
