//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 02:10:24 PM CST 
//


package org.mesa.xml.b2mml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for OpSegmentRequirementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpSegmentRequirementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/B2MML-V0600}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="HierarchyScope" type="{http://www.mesa.org/xml/B2MML-V0600}HierarchyScopeType" minOccurs="0"/>
 *         &lt;element name="OperationsType" type="{http://www.mesa.org/xml/B2MML-V0600}OperationsTypeType" minOccurs="0"/>
 *         &lt;element name="ProcessSegmentID" type="{http://www.mesa.org/xml/B2MML-V0600}ProcessSegmentIDType" minOccurs="0"/>
 *         &lt;element name="EarliestStartTime" type="{http://www.mesa.org/xml/B2MML-V0600}EarliestStartTimeType" minOccurs="0"/>
 *         &lt;element name="LatestEndTime" type="{http://www.mesa.org/xml/B2MML-V0600}LatestEndTimeType" minOccurs="0"/>
 *         &lt;element name="Duration" type="{http://www.mesa.org/xml/B2MML-V0600}DurationType" minOccurs="0"/>
 *         &lt;element name="OperationsDefinitionID" type="{http://www.mesa.org/xml/B2MML-V0600}OperationsDefinitionIDType" minOccurs="0"/>
 *         &lt;element name="SegmentState" type="{http://www.mesa.org/xml/B2MML-V0600}RequestStateType" minOccurs="0"/>
 *         &lt;element name="SegmentParameter" type="{http://www.mesa.org/xml/B2MML-V0600}ParameterType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PersonnelRequirement" type="{http://www.mesa.org/xml/B2MML-V0600}OpPersonnelRequirementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EquipmentRequirement" type="{http://www.mesa.org/xml/B2MML-V0600}OpEquipmentRequirementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PhysicalAssetRequirement" type="{http://www.mesa.org/xml/B2MML-V0600}OpPhysicalAssetRequirementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MaterialRequirement" type="{http://www.mesa.org/xml/B2MML-V0600}OpMaterialRequirementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SegmentRequirement" type="{http://www.mesa.org/xml/B2MML-V0600}OpSegmentRequirementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RequiredByRequestedSegmentResponse" type="{http://www.mesa.org/xml/B2MML-V0600}RequiredByRequestedSegmentResponseType" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-V0600-AllExtensions}OpSegmentRequirement" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpSegmentRequirementType", propOrder = {
    "id",
    "description",
    "hierarchyScope",
    "operationsType",
    "processSegmentID",
    "earliestStartTime",
    "latestEndTime",
    "duration",
    "operationsDefinitionID",
    "segmentState",
    "segmentParameter",
    "personnelRequirement",
    "equipmentRequirement",
    "physicalAssetRequirement",
    "materialRequirement",
    "segmentRequirement",
    "requiredByRequestedSegmentResponse"
})
public class OpSegmentRequirementType {

    @XmlElement(name = "ID")
    protected IdentifierType id;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "HierarchyScope")
    protected HierarchyScopeType hierarchyScope;
    @XmlElement(name = "OperationsType")
    protected OperationsTypeType operationsType;
    @XmlElement(name = "ProcessSegmentID")
    protected ProcessSegmentIDType processSegmentID;
    @XmlElement(name = "EarliestStartTime")
    protected EarliestStartTimeType earliestStartTime;
    @XmlElement(name = "LatestEndTime")
    protected LatestEndTimeType latestEndTime;
    @XmlElement(name = "Duration")
    protected Duration duration;
    @XmlElement(name = "OperationsDefinitionID")
    protected OperationsDefinitionIDType operationsDefinitionID;
    @XmlElement(name = "SegmentState")
    protected RequestStateType segmentState;
    @XmlElement(name = "SegmentParameter")
    protected List<ParameterType> segmentParameter;
    @XmlElement(name = "PersonnelRequirement")
    protected List<OpPersonnelRequirementType> personnelRequirement;
    @XmlElement(name = "EquipmentRequirement")
    protected List<OpEquipmentRequirementType> equipmentRequirement;
    @XmlElement(name = "PhysicalAssetRequirement")
    protected List<OpPhysicalAssetRequirementType> physicalAssetRequirement;
    @XmlElement(name = "MaterialRequirement")
    protected List<OpMaterialRequirementType> materialRequirement;
    @XmlElement(name = "SegmentRequirement")
    protected List<OpSegmentRequirementType> segmentRequirement;
    @XmlElement(name = "RequiredByRequestedSegmentResponse")
    protected RequiredByRequestedSegmentResponseType requiredByRequestedSegmentResponse;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the hierarchyScope property.
     * 
     * @return
     *     possible object is
     *     {@link HierarchyScopeType }
     *     
     */
    public HierarchyScopeType getHierarchyScope() {
        return hierarchyScope;
    }

    /**
     * Sets the value of the hierarchyScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link HierarchyScopeType }
     *     
     */
    public void setHierarchyScope(HierarchyScopeType value) {
        this.hierarchyScope = value;
    }

    /**
     * Gets the value of the operationsType property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsTypeType }
     *     
     */
    public OperationsTypeType getOperationsType() {
        return operationsType;
    }

    /**
     * Sets the value of the operationsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsTypeType }
     *     
     */
    public void setOperationsType(OperationsTypeType value) {
        this.operationsType = value;
    }

    /**
     * Gets the value of the processSegmentID property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessSegmentIDType }
     *     
     */
    public ProcessSegmentIDType getProcessSegmentID() {
        return processSegmentID;
    }

    /**
     * Sets the value of the processSegmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessSegmentIDType }
     *     
     */
    public void setProcessSegmentID(ProcessSegmentIDType value) {
        this.processSegmentID = value;
    }

    /**
     * Gets the value of the earliestStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link EarliestStartTimeType }
     *     
     */
    public EarliestStartTimeType getEarliestStartTime() {
        return earliestStartTime;
    }

    /**
     * Sets the value of the earliestStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link EarliestStartTimeType }
     *     
     */
    public void setEarliestStartTime(EarliestStartTimeType value) {
        this.earliestStartTime = value;
    }

    /**
     * Gets the value of the latestEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link LatestEndTimeType }
     *     
     */
    public LatestEndTimeType getLatestEndTime() {
        return latestEndTime;
    }

    /**
     * Sets the value of the latestEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link LatestEndTimeType }
     *     
     */
    public void setLatestEndTime(LatestEndTimeType value) {
        this.latestEndTime = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDuration(Duration value) {
        this.duration = value;
    }

    /**
     * Gets the value of the operationsDefinitionID property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsDefinitionIDType }
     *     
     */
    public OperationsDefinitionIDType getOperationsDefinitionID() {
        return operationsDefinitionID;
    }

    /**
     * Sets the value of the operationsDefinitionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsDefinitionIDType }
     *     
     */
    public void setOperationsDefinitionID(OperationsDefinitionIDType value) {
        this.operationsDefinitionID = value;
    }

    /**
     * Gets the value of the segmentState property.
     * 
     * @return
     *     possible object is
     *     {@link RequestStateType }
     *     
     */
    public RequestStateType getSegmentState() {
        return segmentState;
    }

    /**
     * Sets the value of the segmentState property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestStateType }
     *     
     */
    public void setSegmentState(RequestStateType value) {
        this.segmentState = value;
    }

    /**
     * Gets the value of the segmentParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the segmentParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegmentParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterType }
     * 
     * 
     */
    public List<ParameterType> getSegmentParameter() {
        if (segmentParameter == null) {
            segmentParameter = new ArrayList<ParameterType>();
        }
        return this.segmentParameter;
    }

    /**
     * Gets the value of the personnelRequirement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personnelRequirement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonnelRequirement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpPersonnelRequirementType }
     * 
     * 
     */
    public List<OpPersonnelRequirementType> getPersonnelRequirement() {
        if (personnelRequirement == null) {
            personnelRequirement = new ArrayList<OpPersonnelRequirementType>();
        }
        return this.personnelRequirement;
    }

    /**
     * Gets the value of the equipmentRequirement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentRequirement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentRequirement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpEquipmentRequirementType }
     * 
     * 
     */
    public List<OpEquipmentRequirementType> getEquipmentRequirement() {
        if (equipmentRequirement == null) {
            equipmentRequirement = new ArrayList<OpEquipmentRequirementType>();
        }
        return this.equipmentRequirement;
    }

    /**
     * Gets the value of the physicalAssetRequirement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physicalAssetRequirement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysicalAssetRequirement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpPhysicalAssetRequirementType }
     * 
     * 
     */
    public List<OpPhysicalAssetRequirementType> getPhysicalAssetRequirement() {
        if (physicalAssetRequirement == null) {
            physicalAssetRequirement = new ArrayList<OpPhysicalAssetRequirementType>();
        }
        return this.physicalAssetRequirement;
    }

    /**
     * Gets the value of the materialRequirement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the materialRequirement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaterialRequirement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpMaterialRequirementType }
     * 
     * 
     */
    public List<OpMaterialRequirementType> getMaterialRequirement() {
        if (materialRequirement == null) {
            materialRequirement = new ArrayList<OpMaterialRequirementType>();
        }
        return this.materialRequirement;
    }

    /**
     * Gets the value of the segmentRequirement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the segmentRequirement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegmentRequirement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpSegmentRequirementType }
     * 
     * 
     */
    public List<OpSegmentRequirementType> getSegmentRequirement() {
        if (segmentRequirement == null) {
            segmentRequirement = new ArrayList<OpSegmentRequirementType>();
        }
        return this.segmentRequirement;
    }

    /**
     * Gets the value of the requiredByRequestedSegmentResponse property.
     * 
     * @return
     *     possible object is
     *     {@link RequiredByRequestedSegmentResponseType }
     *     
     */
    public RequiredByRequestedSegmentResponseType getRequiredByRequestedSegmentResponse() {
        return requiredByRequestedSegmentResponse;
    }

    /**
     * Sets the value of the requiredByRequestedSegmentResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequiredByRequestedSegmentResponseType }
     *     
     */
    public void setRequiredByRequestedSegmentResponse(RequiredByRequestedSegmentResponseType value) {
        this.requiredByRequestedSegmentResponse = value;
    }

}
