//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 02:10:24 PM CST 
//


package org.mesa.xml.b2mml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductionParameterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductionParameterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductSegmentID" type="{http://www.mesa.org/xml/B2MML-V0600}ProductSegmentIDType" minOccurs="0"/>
 *         &lt;element name="ProcessSegmentID" type="{http://www.mesa.org/xml/B2MML-V0600}ProcessSegmentIDType" minOccurs="0"/>
 *         &lt;element name="Parameter" type="{http://www.mesa.org/xml/B2MML-V0600}ParameterType" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-V0600-AllExtensions}ProductionParameter" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductionParameterType", propOrder = {
    "productSegmentID",
    "processSegmentID",
    "parameter"
})
public class ProductionParameterType {

    @XmlElement(name = "ProductSegmentID")
    protected ProductSegmentIDType productSegmentID;
    @XmlElement(name = "ProcessSegmentID")
    protected ProcessSegmentIDType processSegmentID;
    @XmlElement(name = "Parameter")
    protected ParameterType parameter;

    /**
     * Gets the value of the productSegmentID property.
     * 
     * @return
     *     possible object is
     *     {@link ProductSegmentIDType }
     *     
     */
    public ProductSegmentIDType getProductSegmentID() {
        return productSegmentID;
    }

    /**
     * Sets the value of the productSegmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductSegmentIDType }
     *     
     */
    public void setProductSegmentID(ProductSegmentIDType value) {
        this.productSegmentID = value;
    }

    /**
     * Gets the value of the processSegmentID property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessSegmentIDType }
     *     
     */
    public ProcessSegmentIDType getProcessSegmentID() {
        return processSegmentID;
    }

    /**
     * Sets the value of the processSegmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessSegmentIDType }
     *     
     */
    public void setProcessSegmentID(ProcessSegmentIDType value) {
        this.processSegmentID = value;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterType }
     *     
     */
    public ParameterType getParameter() {
        return parameter;
    }

    /**
     * Sets the value of the parameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterType }
     *     
     */
    public void setParameter(ParameterType value) {
        this.parameter = value;
    }

}
