//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 02:10:24 PM CST 
//


package org.mesa.xml.b2mml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StepType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StepType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/B2MML-V0600}IDType"/>
 *         &lt;element name="RecipeElementID" type="{http://www.mesa.org/xml/B2MML-V0600}RecipeElementIDType"/>
 *         &lt;element name="RecipeElementVersion" type="{http://www.mesa.org/xml/B2MML-V0600}RecipeElementVersionType"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/B2MML-V0600}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-V0600-AllExtensions}Step" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StepType", propOrder = {
    "id",
    "recipeElementID",
    "recipeElementVersion",
    "description"
})
public class StepType {

    @XmlElement(name = "ID", required = true)
    protected IDType id;
    @XmlElement(name = "RecipeElementID", required = true)
    protected RecipeElementIDType recipeElementID;
    @XmlElement(name = "RecipeElementVersion", required = true)
    protected RecipeElementVersionType recipeElementVersion;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setID(IDType value) {
        this.id = value;
    }

    /**
     * Gets the value of the recipeElementID property.
     * 
     * @return
     *     possible object is
     *     {@link RecipeElementIDType }
     *     
     */
    public RecipeElementIDType getRecipeElementID() {
        return recipeElementID;
    }

    /**
     * Sets the value of the recipeElementID property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipeElementIDType }
     *     
     */
    public void setRecipeElementID(RecipeElementIDType value) {
        this.recipeElementID = value;
    }

    /**
     * Gets the value of the recipeElementVersion property.
     * 
     * @return
     *     possible object is
     *     {@link RecipeElementVersionType }
     *     
     */
    public RecipeElementVersionType getRecipeElementVersion() {
        return recipeElementVersion;
    }

    /**
     * Sets the value of the recipeElementVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipeElementVersionType }
     *     
     */
    public void setRecipeElementVersion(RecipeElementVersionType value) {
        this.recipeElementVersion = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

}
